"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
export type OpsState={error?:string;success?:string};const condition=z.enum(["operational","needs_repair","retired"]);const date=z.iso.date();async function rpc(name:string,args:Record<string,unknown>){return(await createClient()).rpc(name,args)}
export async function addAssetAction(_s:OpsState,f:FormData):Promise<OpsState>{await requireRole(["owner"]);const p=z.object({name:z.string().trim().min(2).max(120),category:z.string().trim().min(2).max(80),serial:z.string().trim().max(120).optional(),condition,date:date.optional(),note:z.string().trim().max(500).optional()}).safeParse({name:f.get("name"),category:f.get("category"),serial:f.get("serial")||undefined,condition:f.get("condition"),date:f.get("date")||undefined,note:f.get("note")||undefined});if(!p.success)return{error:"সম্পদের তথ্য যাচাই করুন"};const{error}=await rpc("register_center_asset",{p_name:p.data.name,p_category:p.data.category,p_serial:p.data.serial??null,p_condition:p.data.condition,p_acquired_on:p.data.date??null,p_note:p.data.note??null});if(error)return{error:"সম্পদ সংরক্ষণ করা যায়নি।"};revalidatePath("/owner/operations");return{success:"সম্পদ নিবন্ধনে যোগ হয়েছে।"}}
export async function changeAssetAction(_s:OpsState,f:FormData):Promise<OpsState>{await requireRole(["owner"]);const p=z.object({id:z.uuid(),condition,note:z.string().trim().min(3).max(500)}).safeParse({id:f.get("id"),condition:f.get("condition"),note:f.get("note")});if(!p.success)return{error:"অবস্থা ও মন্তব্য যাচাই করুন"};const{error}=await rpc("update_asset_condition",{p_asset_id:p.data.id,p_condition:p.data.condition,p_note:p.data.note});if(error)return{error:"সম্পদের অবস্থা পরিবর্তন করা যায়নি।"};revalidatePath("/owner/operations");return{success:"সম্পদের অবস্থা হালনাগাদ হয়েছে।"}}
export async function runAuditAction(_s:OpsState,f:FormData):Promise<OpsState>{await requireRole(["owner"]);const p=z.object({date,notes:z.string().trim().min(10).max(1000)}).safeParse({date:f.get("date"),notes:f.get("notes")});if(!p.success)return{error:"পরিদর্শনের তথ্য যাচাই করুন"};const{error}=await rpc("run_center_self_audit",{p_inspection_date:p.data.date,p_notes:p.data.notes});if(error)return{error:error.message.includes("already")?"এই তারিখে স্ব-নিরীক্ষা হয়েছে।":"স্ব-নিরীক্ষা সংরক্ষণ করা যায়নি।"};revalidatePath("/owner/operations");return{success:"পরিদর্শনের snapshot সংরক্ষিত হয়েছে।"}}
export async function addComplaintAction(_s:OpsState,f:FormData):Promise<OpsState>{await requireRole(["owner"]);const p=z.object({name:z.string().trim().max(120).optional(),mobile:z.string().regex(/^01[3-9][0-9]{8}$/).optional(),subject:z.string().trim().min(3).max(160),details:z.string().trim().min(10).max(1000)}).safeParse({name:f.get("name")||undefined,mobile:f.get("mobile")||undefined,subject:f.get("subject"),details:f.get("details")});if(!p.success)return{error:"অভিযোগের তথ্য যাচাই করুন"};const{data,error}=await rpc("record_center_complaint",{p_name:p.data.name??null,p_mobile:p.data.mobile??null,p_subject:p.data.subject,p_details:p.data.details});if(error)return{error:"অভিযোগ সংরক্ষণ করা যায়নি।"};revalidatePath("/owner/operations");return{success:`অভিযোগ নম্বর: ${String(data)}`}}
export async function resolveComplaintAction(_s:OpsState,f:FormData):Promise<OpsState>{await requireRole(["owner"]);const p=z.object({id:z.uuid(),resolution:z.string().trim().min(10).max(1000)}).safeParse({id:f.get("id"),resolution:f.get("resolution")});if(!p.success)return{error:"সমাধানের বিবরণ লিখুন"};const{error}=await rpc("resolve_center_complaint",{p_complaint_id:p.data.id,p_resolution:p.data.resolution});if(error)return{error:"অভিযোগ সমাধান করা যায়নি।"};revalidatePath("/owner/operations");return{success:"অভিযোগ সমাধান করা হয়েছে।"}}
