"use client";
import { useActionState, type ReactNode } from "react";
import { AlertCircle, CheckCircle2, LoaderCircle, Play, Save } from "lucide-react";
import { assignSubscriptionAction,enforceOverdueAction,recordPaymentAction,updatePricingAction,type BillingState } from "@/app/superadmin/subscriptions/actions";
const initial:BillingState={};
const input="h-10 w-full rounded-lg border border-border bg-white px-3 text-xs outline-none focus:border-brand";

export function PricingForm({monthly,yearly,grace}:{monthly:number;yearly:number;grace:number}){const[s,a,p]=useActionState(updatePricingAction,initial);return <form action={a} className="mt-5 grid gap-3 sm:grid-cols-3"><Field label="মাসিক মূল্য"><input className={input} name="monthlyFee" type="number" min="0" step="0.01" defaultValue={monthly}/></Field><Field label="বার্ষিক মূল্য"><input className={input} name="yearlyFee" type="number" min="0" step="0.01" defaultValue={yearly}/></Field><Field label="Grace period (দিন)"><input className={input} name="graceDays" type="number" min="0" max="90" defaultValue={grace}/></Field><div className="sm:col-span-2"><Field label="পরিবর্তনের কারণ"><input className={input} name="reason" required minLength={10} maxLength={500}/></Field></div><Submit pending={p}/><Result state={s}/></form>}

export function AssignForm({centerId}:{centerId:string}){const[s,a,p]=useActionState(assignSubscriptionAction,initial);return <form action={a} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="centerId" value={centerId}/><Field label="Billing cycle"><select name="billingCycle" className={input}><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></Field><Field label="শুরুর তারিখ"><input name="startDate" type="date" required defaultValue={new Date().toISOString().slice(0,10)} className={input}/></Field><div className="sm:col-span-2"><Field label="Assignment কারণ"><input name="reason" required minLength={10} maxLength={500} className={input}/></Field></div><Result state={s}/><Submit pending={p} label="Assign করুন"/></form>}

export function PaymentForm({subscriptionId}:{subscriptionId:string}){const[s,a,p]=useActionState(recordPaymentAction,initial);return <form action={a} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="subscriptionId" value={subscriptionId}/><Field label="Payment method"><select name="paymentMethod" className={input}><option value="bank_transfer">Bank transfer</option><option value="mobile_financial_service">MFS</option><option value="cash">Cash</option><option value="other">Other</option></select></Field><Field label="Reference / transaction ID"><input name="paymentReference" required minLength={3} maxLength={120} className={input}/></Field><Result state={s}/><Submit pending={p} label="পরিশোধের রেকর্ড করুন"/></form>}

export function OverdueForm(){const[s,a,p]=useActionState(enforceOverdueAction,initial);return <form action={a}><button disabled={p} className="flex h-10 items-center gap-2 rounded-xl bg-amber-600 px-4 text-xs font-bold text-white disabled:opacity-60">{p?<LoaderCircle className="size-4 animate-spin"/>:<Play className="size-4"/>} Overdue policy চালান</button><Result state={s}/></form>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-1.5 block text-[10px] font-bold text-muted">{label}</span>{children}</label>}
function Submit({pending,label="সংরক্ষণ"}:{pending:boolean;label?:string}){return <button disabled={pending} className="flex h-10 items-center justify-center gap-2 self-end rounded-lg bg-brand px-4 text-xs font-bold text-white disabled:opacity-60">{pending?<LoaderCircle className="size-4 animate-spin"/>:<Save className="size-4"/>}{label}</button>}
function Result({state}:{state:BillingState}){if(!state.error&&!state.success)return <div/>;const bad=!!state.error;return <div className={`flex items-center gap-2 text-[10px] font-semibold ${bad?"text-red-700":"text-emerald-700"}`}>{bad?<AlertCircle className="size-3.5"/>:<CheckCircle2 className="size-3.5"/>}{state.error??state.success}</div>}
