"use client";
import { useActionState, type ReactNode } from "react";
import { AlertCircle, CheckCircle2, LoaderCircle, RotateCcw, Save } from "lucide-react";
import { closeDailyCashAction,recordExpenseAction,reverseExpenseAction,type FinanceState } from "@/app/owner/finance/actions";
const initial:FinanceState={};const field="h-10 w-full rounded-lg border border-border bg-white px-3 text-xs outline-none focus:border-brand";
export function ExpenseForm(){const[s,a,p]=useActionState(recordExpenseAction,initial);return <form action={a} className="mt-5 grid gap-4 sm:grid-cols-2"><Label text="খরচের ধরন"><select name="category" className={field}><option value="rent">ভাড়া</option><option value="electricity">বিদ্যুৎ</option><option value="internet">ইন্টারনেট</option><option value="salary">বেতন</option><option value="supplies">উপকরণ</option><option value="maintenance">রক্ষণাবেক্ষণ</option><option value="other">অন্যান্য</option></select></Label><Label text="পরিমাণ"><input name="amount" type="number" min="0.01" max="10000000" step="0.01" required className={field}/></Label><Label text="তারিখ"><input name="expenseDate" type="date" max={new Date().toISOString().slice(0,10)} defaultValue={new Date().toISOString().slice(0,10)} required className={field}/></Label><Label text="Reference (ঐচ্ছিক)"><input name="reference" maxLength={120} className={field}/></Label><div className="sm:col-span-2"><Label text="বিবরণ"><input name="description" required minLength={3} maxLength={500} className={field}/></Label></div><Result state={s}/><Submit pending={p} label="খরচ সংরক্ষণ"/></form>}
export function CashClosingForm(){const[s,a,p]=useActionState(closeDailyCashAction,initial);return <form action={a} className="mt-5 grid gap-4 sm:grid-cols-2"><Label text="Closing date"><input name="closingDate" type="date" max={new Date().toISOString().slice(0,10)} defaultValue={new Date().toISOString().slice(0,10)} required className={field}/></Label><div/><Label text="Cash"><input name="cash" type="number" min="0" step="0.01" defaultValue="0" required className={field}/></Label><Label text="bKash"><input name="bkash" type="number" min="0" step="0.01" defaultValue="0" required className={field}/></Label><Label text="Nagad"><input name="nagad" type="number" min="0" step="0.01" defaultValue="0" required className={field}/></Label><Label text="Bank"><input name="bank" type="number" min="0" step="0.01" defaultValue="0" required className={field}/></Label><div className="sm:col-span-2"><Label text="মন্তব্য (ঐচ্ছিক)"><input name="note" maxLength={500} className={field}/></Label></div><Result state={s}/><Submit pending={p} label="দিনটি close করুন"/></form>}
export function ReverseExpenseForm({expenseId}:{expenseId:string}){const[s,a,p]=useActionState(reverseExpenseAction,initial);return <form action={a} className="mt-3 flex flex-col gap-2 sm:flex-row"><input type="hidden" name="expenseId" value={expenseId}/><input name="reason" required minLength={10} maxLength={500} placeholder="বাতিলকরণের কারণ" className={`${field} flex-1`}/><button disabled={p} className="flex h-10 items-center justify-center gap-2 rounded-lg border border-red-200 px-3 text-[10px] font-bold text-red-700 disabled:opacity-60">{p?<LoaderCircle className="size-3.5 animate-spin"/>:<RotateCcw className="size-3.5"/>}Reverse</button>{(s.error||s.success)&&<Result state={s}/>}</form>}
function Label({text,children}:{text:string;children:ReactNode}){return <label><span className="mb-1.5 block text-[10px] font-bold text-muted">{text}</span>{children}</label>}
function Submit({pending,label}:{pending:boolean;label:string}){return <button disabled={pending} className="flex h-10 items-center justify-center gap-2 rounded-lg bg-brand px-4 text-xs font-bold text-white disabled:opacity-60">{pending?<LoaderCircle className="size-4 animate-spin"/>:<Save className="size-4"/>}{label}</button>}
function Result({state}:{state:FinanceState}){const bad=!!state.error;return <div className={`flex items-center gap-2 text-[10px] font-semibold ${bad?"text-red-700":"text-emerald-700"}`}>{bad?<AlertCircle className="size-3.5"/>:<CheckCircle2 className="size-3.5"/>}{state.error??state.success}</div>}
