"use client";
import { useActionState } from "react";
import { CheckCircle2,LoaderCircle,Save,Send,Upload } from "lucide-react";
import { attestComplianceAction,submitRenewalAction,uploadLicenseEvidenceAction,type ComplianceState } from "@/app/owner/compliance/actions";
const init:ComplianceState={};const input="h-10 w-full rounded-lg border border-border px-3 text-xs outline-none focus:border-brand";
export function RenewalForm(){const[s,a,p]=useActionState(submitRenewalAction,init);return <form action={a} className="mt-5 grid gap-3 sm:grid-cols-2"><label><span className="mb-1 block text-[10px] font-bold text-muted">নতুন লাইসেন্স নম্বর (ঐচ্ছিক)</span><input name="licenseNumber" maxLength={120} className={input}/></label><label><span className="mb-1 block text-[10px] font-bold text-muted">নতুন মেয়াদ</span><input name="expiresAt" type="date" required className={input}/></label><label className="sm:col-span-2"><span className="mb-1 block text-[10px] font-bold text-muted">নবায়নের বিবরণ</span><input name="note" required minLength={10} maxLength={1000} className={input}/></label><Message state={s}/><button disabled={p} className="flex h-10 items-center justify-center gap-2 rounded-lg bg-brand text-xs font-bold text-white disabled:opacity-60">{p?<LoaderCircle className="size-4 animate-spin"/>:<Send className="size-4"/>}অনুরোধ জমা দিন</button></form>}
export function ComplianceForm({requirement,compliant}:{requirement:string;compliant:boolean}){const[s,a,p]=useActionState(attestComplianceAction,init);return <form action={a} className="mt-3"><input type="hidden" name="requirement" value={requirement}/><input type="hidden" name="state" value={String(!compliant)}/><input name="note" maxLength={500} placeholder="সংক্ষিপ্ত মন্তব্য (ঐচ্ছিক)" className={input}/><button disabled={p} className={`mt-2 flex h-9 w-full items-center justify-center gap-2 rounded-lg text-[10px] font-bold text-white disabled:opacity-60 ${compliant?"bg-slate-600":"bg-brand"}`}>{p?<LoaderCircle className="size-3.5 animate-spin"/>:<Save className="size-3.5"/>}{compliant?"Not compliant করুন":"Compliant করুন"}</button><Message state={s}/></form>}
export function LicenseEvidenceForm({renewalRequestId}:{renewalRequestId?:string}){const[s,a,p]=useActionState(uploadLicenseEvidenceAction,init);return <form action={a} className="rounded-2xl border border-border bg-white p-5 shadow-sm">{renewalRequestId&&<input type="hidden" name="renewalRequestId" value={renewalRequestId}/>}<h2 className="text-sm font-extrabold">এনক্রিপ্টেড লাইসেন্স প্রমাণপত্র</h2><p className="mt-1 text-[10px] leading-5 text-muted">Form-2, জেলা প্রশাসকের চিঠি বা বর্তমান লাইসেন্স AES-256-GCM দিয়ে এনক্রিপ্ট হবে। সর্বোচ্চ ১০ মেগাবাইট।</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><select name="documentType" className={input}><option value="form_2">Form-2</option><option value="dc_letter">জেলা প্রশাসকের চিঠি</option><option value="current_license">বর্তমান লাইসেন্স</option></select><input name="document" type="file" required accept="application/pdf,image/png,image/jpeg,image/webp" className="block h-10 w-full rounded-lg border border-border p-2 text-[10px]"/></div><Message state={s}/><button disabled={p} className="mt-3 flex h-10 items-center justify-center gap-2 rounded-lg bg-brand px-5 text-xs font-bold text-white disabled:opacity-60">{p?<LoaderCircle className="size-4 animate-spin"/>:<Upload className="size-4"/>}এনক্রিপ্ট করে আপলোড</button></form>}
function Message({state}:{state:ComplianceState}){if(!state.error&&!state.success)return <div/>;return <p className={`mt-2 flex items-center gap-1 text-[9px] ${state.error?"text-red-700":"text-emerald-700"}`}><CheckCircle2 className="size-3"/>{state.error??state.success}</p>}
