import type { Metadata } from "next";
import Link from "next/link";
import { CalendarClock, CreditCard, ExternalLink, ReceiptText, ShieldCheck, WalletCards } from "lucide-react";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
export const metadata:Metadata={title:"আমার সাবস্ক্রিপশন"};
type Sub={id:string;billing_cycle:string;status:string;current_period_start:string;current_period_end:string};
type Payment={id:string;voucher_number:string;amount:number|string;payment_method:string;payment_reference:string;paid_at:string;period_start:string;period_end:string};
type Price={monthly_fee:number|string;yearly_fee:number|string;grace_days:number};
const money=new Intl.NumberFormat("bn-BD",{style:"currency",currency:"BDT",maximumFractionDigits:2});
const tone:Record<string,string>={active:"bg-emerald-50 text-emerald-700",pending:"bg-amber-50 text-amber-700",past_due:"bg-orange-50 text-orange-700",suspended:"bg-red-50 text-red-700",cancelled:"bg-slate-100 text-slate-600"};
export default async function OwnerSubscriptionPage(){const context=await requireRole(["owner"],{allowInactiveCenter:true});const sb=await createClient();const[{data:subData},{data:paymentData},{data:priceData}]=await Promise.all([sb.from("center_subscriptions").select("id,billing_cycle,status,current_period_start,current_period_end").eq("center_id",context.centerId!).maybeSingle(),sb.from("subscription_payments").select("id,voucher_number,amount,payment_method,payment_reference,paid_at,period_start,period_end").eq("center_id",context.centerId!).order("paid_at",{ascending:false}),sb.from("subscription_pricing").select("monthly_fee,yearly_fee,grace_days").single()]);const sub=subData as Sub|null;const payments=(paymentData??[]) as Payment[];const price=priceData as Price|null;
return <div><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-xs font-bold text-brand"><WalletCards className="size-4"/> কেন্দ্রের বিলিং</div><h1 className="mt-2 text-2xl font-extrabold sm:text-3xl">আমার সাবস্ক্রিপশন</h1><p className="mt-2 text-sm text-muted">{context.centerName}-এর পরিকল্পনা, মেয়াদ ও পরিশোধের ভাউচার।</p></div><div className="flex w-fit items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-xs font-bold text-emerald-800"><ShieldCheck className="size-4"/> শুধু-পঠনযোগ্য বিলিং রেকর্ড</div></div>
{!sub?<section className="rounded-2xl border border-amber-200 bg-amber-50 p-7 text-center"><CreditCard className="mx-auto size-10 text-amber-700"/><h2 className="mt-3 text-lg font-extrabold text-amber-950">সাবস্ক্রিপশন assign করা হয়নি</h2><p className="mt-2 text-xs text-amber-800">Platform administration-এর সঙ্গে যোগাযোগ করুন।</p></section>:<section className="rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs text-muted">বর্তমান plan</p><h2 className="mt-1 text-xl font-extrabold capitalize">{sub.billing_cycle}</h2></div><span className={`w-fit rounded-full px-3 py-1.5 text-[10px] font-extrabold uppercase ${tone[sub.status]??tone.cancelled}`}>{sub.status}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Info label="বর্তমান মূল্য" value={price?money.format(Number(sub.billing_cycle==="monthly"?price.monthly_fee:price.yearly_fee)):"—"}/><Info label="মেয়াদ শুরু" value={sub.current_period_start}/><Info label="মেয়াদ শেষ" value={sub.current_period_end}/></div>{price&&<p className="mt-4 flex items-center gap-2 rounded-xl bg-brand-soft/60 p-3 text-[10px] text-brand"><CalendarClock className="size-4"/> মেয়াদ শেষে {price.grace_days} দিনের grace period প্রযোজ্য।</p>}</section>}
<section className="mt-6 overflow-hidden rounded-2xl border border-border bg-white shadow-sm"><div className="border-b border-border p-5 sm:p-6"><div className="flex items-center gap-2"><ReceiptText className="size-5 text-brand"/><h2 className="text-base font-extrabold">Payment history</h2></div><p className="mt-1 text-[10px] text-muted">Voucher অপরিবর্তনীয় এবং print-ready</p></div>{payments.length===0?<p className="py-14 text-center text-xs text-muted">এখনো কোনো পরিশোধ record নেই</p>:<div className="divide-y divide-border">{payments.map(payment=><div key={payment.id} className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div><p className="font-mono text-xs font-extrabold text-brand">{payment.voucher_number}</p><p className="mt-1 text-[10px] text-muted">{payment.period_start} — {payment.period_end} • {payment.payment_method}</p></div><div className="flex items-center gap-4"><p className="text-sm font-extrabold">{money.format(Number(payment.amount))}</p><Link href={`/owner/subscription/vouchers/${payment.id}`} className="flex h-9 items-center gap-2 rounded-lg border border-brand/20 px-3 text-[10px] font-bold text-brand">Voucher <ExternalLink className="size-3"/></Link></div></div>)}</div>}</section></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#f7faf8] p-4"><p className="text-[10px] text-muted">{label}</p><p className="mt-1 text-sm font-extrabold">{value}</p></div>}
