"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
export type FinanceState={error?:string;success?:string};
const amount=z.coerce.number().min(0).max(10_000_000);
const category=z.enum(["rent","electricity","internet","salary","supplies","maintenance","other"]);
const expenseSchema=z.object({category,amount:amount.refine(v=>v>0,"Amount শূন্যের বেশি হতে হবে"),expenseDate:z.iso.date(),description:z.string().trim().min(3).max(500),reference:z.string().trim().max(120).optional()});
export async function recordExpenseAction(_state:FinanceState,formData:FormData):Promise<FinanceState>{await requireRole(["owner"]);const p=expenseSchema.safeParse({category:formData.get("category"),amount:formData.get("amount"),expenseDate:formData.get("expenseDate"),description:formData.get("description"),reference:formData.get("reference")||undefined});if(!p.success)return{error:p.error.issues[0]?.message??"খরচের তথ্য যাচাই করুন"};const{error}=await(await createClient()).rpc("record_center_expense",{p_category:p.data.category,p_amount:p.data.amount,p_expense_date:p.data.expenseDate,p_description:p.data.description,p_reference:p.data.reference??null});if(error)return{error:error.message.includes("closed")?"এই দিনের cash closing সম্পন্ন হয়েছে।":"খরচ সংরক্ষণ করা যায়নি।"};revalidatePath("/owner/finance");return{success:"খরচ immutable ledger-এ সংরক্ষিত হয়েছে।"}}
export async function reverseExpenseAction(_state:FinanceState,formData:FormData):Promise<FinanceState>{await requireRole(["owner"]);const p=z.object({expenseId:z.uuid(),reason:z.string().trim().min(10).max(500)}).safeParse({expenseId:formData.get("expenseId"),reason:formData.get("reason")});if(!p.success)return{error:p.error.issues[0]?.message??"Reversal reason লিখুন"};const{error}=await(await createClient()).rpc("reverse_center_expense",{p_expense_id:p.data.expenseId,p_reason:p.data.reason});if(error)return{error:error.message.includes("closed")?"Closed দিনের entry reverse করা যাবে না।":error.message.includes("already")?"Entry ইতোমধ্যে reversed।":"Reversal সংরক্ষণ করা যায়নি।"};revalidatePath("/owner/finance");return{success:"মূল record অক্ষত রেখে reversal entry তৈরি হয়েছে।"}}
export async function closeDailyCashAction(_state:FinanceState,formData:FormData):Promise<FinanceState>{await requireRole(["owner"]);const p=z.object({closingDate:z.iso.date(),cash:amount,bkash:amount,nagad:amount,bank:amount,note:z.string().trim().max(500).optional()}).safeParse({closingDate:formData.get("closingDate"),cash:formData.get("cash"),bkash:formData.get("bkash"),nagad:formData.get("nagad"),bank:formData.get("bank"),note:formData.get("note")||undefined});if(!p.success)return{error:p.error.issues[0]?.message??"Cash closing তথ্য যাচাই করুন"};const{error}=await(await createClient()).rpc("close_daily_cash",{p_closing_date:p.data.closingDate,p_reported_cash:p.data.cash,p_reported_bkash:p.data.bkash,p_reported_nagad:p.data.nagad,p_reported_bank:p.data.bank,p_note:p.data.note??null});if(error)return{error:error.message.includes("already")?"এই দিনের cash closing আগে সম্পন্ন হয়েছে।":"Cash closing সম্পন্ন করা যায়নি।"};revalidatePath("/owner/finance");return{success:"Daily cash closing immutableভাবে সংরক্ষিত হয়েছে।"}}
