import type { Metadata } from "next";
import { Banknote, BookOpen, Calculator, Landmark, ReceiptText, ShieldCheck, TrendingUp } from "lucide-react";
import { CashClosingForm,ExpenseForm,ReverseExpenseForm } from "@/components/finance/FinanceForms";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
export const metadata:Metadata={title:"আয়-ব্যয় ও cash closing"};
type Summary={gross_collection:number|string;government_fee:number|string;assistance_income:number|string;additional_income:number|string;expense_total:number|string;net_center_income:number|string;application_count:number|string};
type Expense={id:string;entry_type:"expense"|"reversal";category:string;amount:number|string;expense_date:string;description:string;reference:string|null;reversed_entry_id:string|null;created_at:string};
type Closing={id:string;closing_date:string;system_collection:number|string;system_expense:number|string;reported_cash:number|string;reported_bkash:number|string;reported_nagad:number|string;reported_bank:number|string;reported_total:number|string;variance:number|string;closed_at:string};
const money=new Intl.NumberFormat("bn-BD",{style:"currency",currency:"BDT",maximumFractionDigits:2});const num=new Intl.NumberFormat("bn-BD");
export default async function FinancePage(){const context=await requireRole(["owner"]);const sb=await createClient();const month=new Date().toISOString().slice(0,8)+"01";const[{data:summaryData},{data:expenseData},{data:closingData}]=await Promise.all([sb.rpc("owner_finance_summary",{p_month:month}),sb.from("center_expense_entries").select("id,entry_type,category,amount,expense_date,description,reference,reversed_entry_id,created_at").eq("center_id",context.centerId!).order("created_at",{ascending:false}).limit(30),sb.from("daily_cash_closings").select("id,closing_date,system_collection,system_expense,reported_cash,reported_bkash,reported_nagad,reported_bank,reported_total,variance,closed_at").eq("center_id",context.centerId!).order("closing_date",{ascending:false}).limit(14)]);const row=(Array.isArray(summaryData)?summaryData[0]:summaryData) as Summary|null;const expenses=(expenseData??[]) as Expense[];const closings=(closingData??[]) as Closing[];const reversed=new Set(expenses.filter(x=>x.entry_type==="reversal").map(x=>x.reversed_entry_id));
return <div><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-xs font-bold text-brand"><Calculator className="size-4"/> কেন্দ্রের হিসাব</div><h1 className="mt-2 text-2xl font-extrabold sm:text-3xl">আয়-ব্যয় ও দৈনিক নগদ হিসাব সমাপনী</h1><p className="mt-2 text-sm text-muted">{context.centerName} • চলতি মাসের হিসাব</p></div><div className="flex w-fit items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-xs font-bold text-emerald-800"><ShieldCheck className="size-4"/> অপরিবর্তনীয় হিসাবখাতা</div></div>
<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="মোট collection" value={money.format(Number(row?.gross_collection??0))} icon={Banknote}/><Metric label="কেন্দ্র service income" value={money.format(Number(row?.assistance_income??0)+Number(row?.additional_income??0))} icon={TrendingUp}/><Metric label="মোট খরচ" value={money.format(Number(row?.expense_total??0))} icon={ReceiptText}/><Metric label="Net center income" value={money.format(Number(row?.net_center_income??0))} icon={Landmark}/></div><p className="mt-3 text-[10px] text-muted">চলতি মাসে {num.format(Number(row?.application_count??0))}টি application • সরকারি ফি {money.format(Number(row?.government_fee??0))}</p>
<div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6"><h2 className="text-base font-extrabold">নতুন খরচ</h2><p className="mt-1 text-[10px] text-muted">ভুল হলে record edit/delete নয়—reversal করতে হবে</p><ExpenseForm/></section><section className="rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6"><h2 className="text-base font-extrabold">Daily cash settlement</h2><p className="mt-1 text-[10px] text-muted">Cash + bKash + Nagad + Bank মোটের সঙ্গে system collection মিলবে</p><CashClosingForm/></section></div>
<section className="mt-6 overflow-hidden rounded-2xl border border-border bg-white shadow-sm"><div className="border-b border-border p-5 sm:p-6"><div className="flex items-center gap-2"><BookOpen className="size-5 text-brand"/><h2 className="text-base font-extrabold">Expense ledger</h2></div></div>{expenses.length===0?<Empty text="এখনো কোনো খরচ নেই"/>:<div className="divide-y divide-border">{expenses.map(item=><div key={item.id} className="p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[8px] font-extrabold uppercase ${item.entry_type==="reversal"?"bg-blue-50 text-blue-700":"bg-rose-50 text-rose-700"}`}>{item.entry_type}</span><p className="text-xs font-bold capitalize">{item.category}</p></div><p className="mt-2 text-[10px] text-muted">{item.expense_date} • {item.description}{item.reference?` • Ref: ${item.reference}`:""}</p></div><p className={`text-sm font-extrabold ${item.entry_type==="reversal"?"text-blue-700":"text-rose-700"}`}>{item.entry_type==="reversal"?"− reversal ":""}{money.format(Number(item.amount))}</p></div>{item.entry_type==="expense"&&!reversed.has(item.id)&&<ReverseExpenseForm expenseId={item.id}/>}</div>)}</div>}</section>
<section className="mt-6 rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6"><h2 className="text-base font-extrabold">Cash closing history</h2>{closings.length===0?<Empty text="এখনো কোনো দিন close করা হয়নি"/>:<div className="mt-5 grid gap-3 lg:grid-cols-2">{closings.map(item=>{const variance=Number(item.variance);return <article key={item.id} className="rounded-xl border border-border p-4"><div className="flex justify-between gap-3"><p className="text-xs font-extrabold">{item.closing_date}</p><span className={`text-xs font-extrabold ${variance===0?"text-emerald-700":"text-red-700"}`}>Variance: {money.format(variance)}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-[9px] text-muted"><span>সিস্টেম: {money.format(Number(item.system_collection))}</span><span>Reported: {money.format(Number(item.reported_total))}</span><span>Cash: {money.format(Number(item.reported_cash))}</span><span>MFS: {money.format(Number(item.reported_bkash)+Number(item.reported_nagad))}</span><span>Bank: {money.format(Number(item.reported_bank))}</span><span>Expense: {money.format(Number(item.system_expense))}</span></div></article>})}</div>}</section></div>}
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:typeof Banknote}){return <article className="rounded-2xl border border-border bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs text-muted">{label}</p><p className="mt-3 text-xl font-extrabold">{value}</p></div><div className="grid size-10 place-items-center rounded-xl bg-brand-soft text-brand"><Icon className="size-5"/></div></div></article>}
function Empty({text}:{text:string}){return <p className="py-12 text-center text-xs text-muted">{text}</p>}
