"use server";
import { createHash } from "node:crypto";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireRole } from "@/lib/auth/session";
import { deleteEncryptedDriveFile,isEncryptedFileStorageConfigured,uploadEncryptedLicenseEvidence } from "@/lib/google-drive/encrypted-file-storage";
import { createClient } from "@/lib/supabase/server";
export type ComplianceState={error?:string;success?:string};
const requirement=z.enum(["dc_approval","valid_license","rate_chart","signboard","citizen_consent","complaint_box","secure_records","inspection_register"]);
export async function submitRenewalAction(_s:ComplianceState,f:FormData):Promise<ComplianceState>{await requireRole(["owner"]);const p=z.object({number:z.string().trim().max(120).optional(),expires:z.iso.date(),note:z.string().trim().min(10).max(1000)}).safeParse({number:f.get("licenseNumber")||undefined,expires:f.get("expiresAt"),note:f.get("note")});if(!p.success)return{error:p.error.issues[0]?.message??"তথ্য যাচাই করুন"};const{error}=await(await createClient()).rpc("submit_license_renewal",{p_requested_license_number:p.data.number??null,p_requested_expires_at:p.data.expires,p_owner_note:p.data.note});if(error)return{error:error.message.includes("already")?"একটি renewal request ইতোমধ্যে pending আছে।":"Renewal request জমা দেওয়া যায়নি।"};revalidatePath("/owner/compliance");revalidatePath("/superadmin/license-renewals");return{success:"License renewal request জমা হয়েছে।"}}
export async function attestComplianceAction(_s:ComplianceState,f:FormData):Promise<ComplianceState>{await requireRole(["owner"]);const p=z.object({requirement,state:z.enum(["true","false"]),note:z.string().trim().max(500).optional()}).safeParse({requirement:f.get("requirement"),state:f.get("state"),note:f.get("note")||undefined});if(!p.success)return{error:"Compliance তথ্য যাচাই করুন"};const{error}=await(await createClient()).rpc("attest_center_compliance",{p_requirement:p.data.requirement,p_is_compliant:p.data.state==="true",p_note:p.data.note??null});if(error)return{error:"Compliance status সংরক্ষণ করা যায়নি।"};revalidatePath("/owner/compliance");return{success:"Compliance attestation সংরক্ষিত।"}}
const MAX_EVIDENCE_BYTES=10*1024*1024;function validEvidence(bytes:Buffer,type:string){if(type==="application/pdf")return bytes.subarray(0,5).toString("ascii")==="%PDF-";if(type==="image/png")return bytes.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]));if(type==="image/jpeg")return bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;if(type==="image/webp")return bytes.subarray(0,4).toString("ascii")==="RIFF"&&bytes.subarray(8,12).toString("ascii")==="WEBP";return false}
export async function uploadLicenseEvidenceAction(_s:ComplianceState,f:FormData):Promise<ComplianceState>{const context=await requireRole(["owner"]);const parsed=z.object({documentType:z.enum(["form_2","dc_letter","current_license"]),renewalRequestId:z.uuid().optional()}).safeParse({documentType:f.get("documentType"),renewalRequestId:f.get("renewalRequestId")||undefined});if(!parsed.success)return{error:"লাইসেন্স প্রমাণপত্রের তথ্য সঠিক নয়।"};const file=f.get("document");if(!(file instanceof File)||file.size<1||file.size>MAX_EVIDENCE_BYTES||!["application/pdf","image/png","image/jpeg","image/webp"].includes(file.type))return{error:"সর্বোচ্চ ১০ মেগাবাইট PDF, PNG, JPEG অথবা WebP ফাইল দিন।"};if(!isEncryptedFileStorageConfigured())return{error:"এনক্রিপ্টেড Google Drive সংরক্ষণ এখনো কনফিগার করা হয়নি।"};const bytes=Buffer.from(await file.arrayBuffer());if(!validEvidence(bytes,file.type))return{error:"ফাইলের প্রকৃত ধরন সঠিক নয়।"};const supabase=await createClient();const{data:center}=await supabase.from("centers").select("code").eq("id",context.centerId!).single();if(!center?.code)return{error:"কেন্দ্রটি পাওয়া যায়নি।"};const hash=createHash("sha256").update(bytes).digest("hex");const encryptedName=`enc_${hash.slice(0,24)}.bin`;try{const uploaded=await uploadEncryptedLicenseEvidence({bytes,encryptedName,centerCode:center.code,documentType:parsed.data.documentType,createdAt:new Date()});const{error}=await supabase.rpc("register_license_evidence",{p_renewal_request_id:parsed.data.renewalRequestId??null,p_document_type:parsed.data.documentType,p_drive_file_id:uploaded.fileId,p_encrypted_file_name:encryptedName,p_file_hash:hash,p_mime_type:file.type,p_plain_size:bytes.length,p_encrypted_size:uploaded.encryptedSize,p_drive_path_key:uploaded.pathKey});if(error){try{await deleteEncryptedDriveFile(uploaded.fileId)}catch{const{error:queueError}=await supabase.rpc("queue_drive_cleanup",{p_center_id:context.centerId!,p_drive_file_id:uploaded.fileId,p_drive_path_key:uploaded.pathKey,p_source_type:"license_evidence",p_reason:"Metadata registration and compensating deletion failed"});return{error:queueError?"প্রমাণপত্র নিবন্ধন ও Drive rollback ব্যর্থ হয়েছে। জরুরি প্রশাসনিক সহায়তা নিন।":"অবশিষ্ট Drive ফাইল প্রশাসনিক পরিচ্ছন্নতা সারিতে যোগ হয়েছে।"}}return{error:"প্রমাণপত্র নিবন্ধন করা যায়নি; অস্থায়ী Drive ফাইল সরানো হয়েছে।"}}}catch{return{error:"প্রমাণপত্রটি এনক্রিপ্ট করে সংরক্ষণ করা যায়নি।"}}revalidatePath("/owner/compliance");revalidatePath("/superadmin/license-renewals");return{success:"লাইসেন্স প্রমাণপত্র এনক্রিপ্ট করে সংরক্ষণ করা হয়েছে।"}}
