import type { Metadata } from "next";
import Link from "next/link";
import { ExternalLink, FileBarChart, FileCheck2, ShieldCheck } from "lucide-react";
import { MonthlyReportForm } from "@/components/reports/MonthlyReportForm";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
export const metadata:Metadata={title:"সরকারি মাসিক রিপোর্ট"};
type Report={id:string;report_month:string;report_number:string;summary_snapshot:Record<string,number>;content_hash:string;generated_at:string};const money=new Intl.NumberFormat("bn-BD",{style:"currency",currency:"BDT",maximumFractionDigits:2});
export default async function ReportsPage(){const context=await requireRole(["owner"]);const{data}=await(await createClient()).from("monthly_government_reports").select("id,report_month,report_number,summary_snapshot,content_hash,generated_at").eq("center_id",context.centerId!).order("report_month",{ascending:false});const reports=(data??[]) as unknown as Report[];return <div><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-xs font-bold text-brand"><FileBarChart className="size-4"/> Government reporting</div><h1 className="mt-2 text-2xl font-extrabold sm:text-3xl">মাসিক সরকারি রিপোর্ট</h1><p className="mt-2 text-sm text-muted">{context.centerName} • Finalized immutable reports</p></div><div className="flex w-fit items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-xs font-bold text-emerald-800"><ShieldCheck className="size-4"/> SHA-256 integrity</div></div><section className="rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6"><h2 className="text-base font-extrabold">নতুন final report</h2><p className="mt-1 text-[10px] leading-5 text-muted">শুধু completed month final করা যায়। মাসের প্রতিটি activity day আগে cash close করতে হবে।</p><MonthlyReportForm/></section><section className="mt-6 overflow-hidden rounded-2xl border border-border bg-white shadow-sm"><div className="border-b border-border p-5 sm:p-6"><h2 className="text-base font-extrabold">Report archive</h2><p className="mt-1 text-[10px] text-muted">Final report edit বা delete করা যায় না</p></div>{reports.length===0?<p className="py-14 text-center text-xs text-muted">এখনো কোনো monthly report তৈরি হয়নি</p>:<div className="divide-y divide-border">{reports.map(report=><div key={report.id} className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-brand-soft text-brand"><FileCheck2 className="size-5"/></div><div><p className="font-mono text-xs font-extrabold text-brand">{report.report_number}</p><p className="mt-1 text-[10px] text-muted">মাস: {new Intl.DateTimeFormat("bn-BD",{month:"long",year:"numeric",timeZone:"Asia/Dhaka"}).format(new Date(`${report.report_month}T00:00:00+06:00`))} • Collection: {money.format(Number(report.summary_snapshot.gross_collection??0))}</p><p className="mt-1 font-mono text-[8px] text-muted">হ্যাশ: {report.content_hash.slice(0,20)}…</p></div></div><Link href={`/owner/reports/${report.id}`} className="flex h-9 items-center justify-center gap-2 rounded-lg border border-brand/20 px-3 text-[10px] font-bold text-brand">রিপোর্ট খুলুন <ExternalLink className="size-3"/></Link></div>)}</div>}</section></div>}
