import type { Metadata } from "next";
import Link from "next/link";
import { Download, Files } from "lucide-react";
import { notFound } from "next/navigation";
import { DocumentUploadForm } from "@/components/applications/DocumentUploadForm";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
export const metadata:Metadata={title:"আবেদনের নথি"};export const dynamic="force-dynamic";
const labels:Record<string,string>={nid:"জাতীয় পরিচয়পত্র",khatian:"খতিয়ান/পর্চা",map:"ম্যাপ/নকশা",application:"আবেদনপত্র",supporting:"সহায়ক নথি",other:"অন্যান্য"};
export default async function DocumentsPage({params}:{params:Promise<{id:string}>}){await requireRole(["operator"]);const{id}=await params;const supabase=await createClient();const[{data:app},{data:docs}]=await Promise.all([supabase.from("applications").select("id,tracking_id,citizen_name,service_code").eq("id",id).single(),supabase.from("application_documents").select("id,document_type,mime_type,plain_size,file_hash,created_at").eq("application_id",id).order("created_at",{ascending:false})]);if(!app)notFound();return <div><div className="mb-7"><div className="flex items-center gap-2 text-xs font-bold text-brand"><Files className="size-4"/> এনক্রিপ্টেড নথি</div><h1 className="mt-2 text-2xl font-extrabold">{app.citizen_name}</h1><p className="mt-2 font-mono text-xs text-muted">{app.tracking_id}</p></div><DocumentUploadForm applicationId={app.id}/><section className="mt-8"><h2 className="mb-4 text-sm font-extrabold">সংরক্ষিত নথি</h2>{!docs?.length?<div className="rounded-2xl border border-dashed border-border bg-white py-12 text-center text-sm text-muted">এখনো কোনো নথি যোগ করা হয়নি।</div>:<div className="grid gap-3 sm:grid-cols-2">{docs.map(doc=><article key={doc.id} className="rounded-2xl border border-border bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-extrabold">{labels[doc.document_type]??"নথি"}</p><p className="mt-1 text-[9px] text-muted">{doc.mime_type} • {new Intl.NumberFormat("bn-BD").format(Math.ceil(doc.plain_size/1024))} কিলোবাইট</p><p className="mt-2 font-mono text-[8px] text-muted">SHA-256: {doc.file_hash.slice(0,16)}…</p></div><Link href={`/api/documents/${doc.id}`} className="grid size-9 place-items-center rounded-lg bg-brand-soft text-brand" aria-label="নথি ডাউনলোড"><Download className="size-4"/></Link></div></article>)}</div>}</section></div>}
