import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, BadgeCheck } from "lucide-react";
import { PrintVoucherButton } from "@/components/billing/PrintVoucherButton";
import { GovernmentMark } from "@/components/common/GovernmentMark";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
export const metadata:Metadata={title:"সাবস্ক্রিপশন পরিশোধ voucher"};
type Voucher={voucher_number:string;amount:number|string;billing_cycle:string;period_start:string;period_end:string;payment_method:string;payment_reference:string;paid_at:string;centers:{code:string;name:string;address:string;license_number:string|null}|null};
const money=new Intl.NumberFormat("bn-BD",{style:"currency",currency:"BDT",minimumFractionDigits:2});
export default async function VoucherPage({params}:{params:Promise<{id:string}>}){const context=await requireRole(["owner"],{allowInactiveCenter:true});const{id}=await params;const{data}=await (await createClient()).from("subscription_payments").select("voucher_number,amount,billing_cycle,period_start,period_end,payment_method,payment_reference,paid_at,centers(code,name,address,license_number)").eq("id",id).eq("center_id",context.centerId!).maybeSingle();if(!data)notFound();const voucher=data as unknown as Voucher;return <div className="mx-auto max-w-3xl"><div className="mb-5 flex items-center justify-between gap-3 print:hidden"><Link href="/owner/subscription" className="flex items-center gap-2 text-xs font-bold text-muted"><ArrowRight className="size-4"/> ফিরে যান</Link><PrintVoucherButton/></div><article className="rounded-2xl border border-border bg-white p-7 shadow-sm print:border-0 print:shadow-none sm:p-10"><header className="flex flex-col justify-between gap-5 border-b-2 border-brand pb-6 sm:flex-row sm:items-start"><GovernmentMark compact/><div className="sm:text-right"><p className="text-[10px] font-bold uppercase tracking-widest text-muted">সাবস্ক্রিপশন পরিশোধ voucher</p><p className="mt-2 font-mono text-sm font-extrabold text-brand">{voucher.voucher_number}</p></div></header><div className="mt-7 grid gap-5 sm:grid-cols-2"><Info label="কেন্দ্র" value={voucher.centers?.name??context.centerName??"—"}/><Info label="কেন্দ্র code" value={voucher.centers?.code??"—"}/><Info label="লাইসেন্স নম্বর" value={voucher.centers?.license_number??"—"}/><Info label="Billing cycle" value={voucher.billing_cycle.toUpperCase()}/><Info label="সাবস্ক্রিপশন period" value={`${voucher.period_start} — ${voucher.period_end}`}/><Info label="Payment date" value={new Intl.DateTimeFormat("bn-BD",{dateStyle:"long",timeStyle:"short",timeZone:"Asia/Dhaka"}).format(new Date(voucher.paid_at))}/><Info label="Payment method" value={voucher.payment_method.replaceAll("_"," ").toUpperCase()}/><Info label="Transaction reference" value={voucher.payment_reference}/></div><div className="mt-7 rounded-2xl bg-brand p-6 text-white"><p className="text-xs text-white/70">পরিশোধিত সাবস্ক্রিপশন fee</p><p className="mt-2 text-3xl font-extrabold">{money.format(Number(voucher.amount))}</p></div><footer className="mt-7 flex items-start gap-3 border-t border-dashed border-border pt-5 text-[10px] leading-5 text-muted"><BadgeCheck className="mt-0.5 size-4 shrink-0 text-brand"/>এই voucher system-generated immutable পরিশোধ record। Voucher number ও transaction reference ব্যবহার করে platform administration record যাচাই করতে পারবে।</footer></article></div>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-[10px] font-semibold text-muted">{label}</p><p className="mt-1 text-xs font-extrabold">{value}</p></div>}
