import type { Metadata } from "next";
import { History, ShieldCheck, WalletCards } from "lucide-react";
import { AssignForm, OverdueForm, PaymentForm, PricingForm } from "@/components/billing/BillingForms";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
export const metadata:Metadata={title:"সাবস্ক্রিপশন ও billing"};
type Sub={id:string;billing_cycle:"monthly"|"yearly";status:string;current_period_start:string;current_period_end:string;center_suspended_for_billing:boolean};
type Center={id:string;code:string;name:string;status:string;center_subscriptions:Sub[]|Sub|null};
type Price={monthly_fee:number|string;yearly_fee:number|string;grace_days:number;effective_from:string};
type Payment={id:string;voucher_number:string;amount:number|string;payment_method:string;payment_reference:string;paid_at:string;centers:{code:string;name:string}|null};
const money=new Intl.NumberFormat("bn-BD",{style:"currency",currency:"BDT",maximumFractionDigits:2});
const statusTone:Record<string,string>={active:"bg-emerald-50 text-emerald-700",pending:"bg-amber-50 text-amber-700",past_due:"bg-orange-50 text-orange-700",suspended:"bg-red-50 text-red-700",cancelled:"bg-slate-100 text-slate-600"};

export default async function SubscriptionsPage(){await requireRole(["super_admin"]);const sb=await createClient();const[{data:pricingData},{data:centerData},{data:payments}]=await Promise.all([sb.from("subscription_pricing").select("monthly_fee,yearly_fee,grace_days,effective_from").single(),sb.from("centers").select("id,code,name,status,center_subscriptions(id,billing_cycle,status,current_period_start,current_period_end,center_suspended_for_billing)").order("name"),sb.from("subscription_payments").select("id,voucher_number,amount,payment_method,payment_reference,paid_at,centers(code,name)").order("paid_at",{ascending:false}).limit(10)]);const pricing=pricingData as Price|null;const centers=(centerData??[]) as unknown as Center[];const rows=centers.map(center=>({center,sub:Array.isArray(center.center_subscriptions)?center.center_subscriptions[0]??null:center.center_subscriptions}));const paid=rows.filter(x=>x.sub?.status==="active").length;const attention=rows.filter(x=>x.sub&&["past_due","suspended"].includes(x.sub.status)).length;
return <div><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-xs font-bold text-brand"><WalletCards className="size-4"/> Fixed-price SaaS</div><h1 className="mt-2 text-2xl font-extrabold sm:text-3xl">সাবস্ক্রিপশন ও center billing</h1><p className="mt-2 text-sm text-muted">Pricing, পরিশোধ, voucher এবং overdue enforcement।</p></div><div className="flex w-fit items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-xs font-bold text-emerald-800"><ShieldCheck className="size-4"/> AAL2-protected</div></div>
<div className="grid gap-4 sm:grid-cols-3"><Stat label="সক্রিয় সাবস্ক্রিপশন" value={paid}/><Stat label="Payment attention" value={attention}/><Stat label="সাবস্ক্রিপশন নেই" value={rows.filter(x=>!x.sub).length}/></div>
{pricing&&<section className="mt-6 rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><h2 className="text-base font-extrabold">Global pricing</h2><p className="mt-1 text-[10px] text-muted">বর্তমান: মাসিক {money.format(Number(pricing.monthly_fee))} • বার্ষিক {money.format(Number(pricing.yearly_fee))} • Grace {pricing.grace_days} দিন</p></div><OverdueForm/></div><PricingForm monthly={Number(pricing.monthly_fee)} yearly={Number(pricing.yearly_fee)} grace={pricing.grace_days}/></section>}
<section className="mt-6 overflow-hidden rounded-2xl border border-border bg-white shadow-sm"><div className="border-b border-border p-5 sm:p-6"><h2 className="text-base font-extrabold">কেন্দ্র সাবস্ক্রিপশনs</h2><p className="mt-1 text-[10px] text-muted">পরিশোধের রেকর্ড হলে নির্ধারিত চক্র অনুযায়ী মেয়াদ বাড়বে</p></div><div className="divide-y divide-border">{rows.map(({center,sub})=><details key={center.id} className="group p-5 open:bg-brand-soft/10"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><div><p className="text-xs font-extrabold sm:text-sm">{center.name}</p><p className="mt-1 font-mono text-[9px] text-muted">{center.code} • Center: {center.status}</p></div><div className="flex items-center gap-3">{sub?<span className={`rounded-full px-2.5 py-1 text-[9px] font-extrabold uppercase ${statusTone[sub.status]??statusTone.cancelled}`}>{sub.status}</span>:<span className="rounded-full bg-slate-100 px-2.5 py-1 text-[9px] font-bold text-slate-600">অনির্ধারিত</span>}<span className="text-lg text-muted transition group-open:rotate-45">+</span></div></summary>{sub?<div className="mt-4 rounded-xl border border-border bg-white p-4"><div className="grid gap-3 text-[10px] sm:grid-cols-3"><Info label="চক্র" value={sub.billing_cycle}/><Info label="মেয়াদ" value={`${sub.current_period_start} — ${sub.current_period_end}`}/><Info label="বিলিং স্থগিত" value={sub.center_suspended_for_billing?"হ্যাঁ":"না"}/></div><PaymentForm subscriptionId={sub.id}/></div>:center.status==="blocked"?<p className="mt-4 rounded-xl bg-red-50 p-4 text-xs text-red-700">অবরুদ্ধ center-এ সাবস্ক্রিপশন assign করা যাবে না।</p>:<AssignForm centerId={center.id}/>}</details>)}</div></section>
<section className="mt-6 rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-2"><History className="size-5 text-brand"/><h2 className="text-base font-extrabold">সাম্প্রতিক পরিশোধ vouchers</h2></div>{!payments?.length?<p className="py-10 text-center text-xs text-muted">এখনো পরিশোধ নেই</p>:<div className="mt-5 grid gap-3 lg:grid-cols-2">{((payments??[]) as unknown as Payment[]).map(p=><article key={p.id} className="rounded-xl border border-border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] font-bold text-brand">{p.voucher_number}</p><p className="mt-1 text-xs font-extrabold">{p.centers?.name??"কেন্দ্র"}</p></div><p className="text-sm font-extrabold">{money.format(Number(p.amount))}</p></div><p className="mt-3 text-[9px] text-muted">{p.payment_method} • {p.payment_reference} • {new Intl.DateTimeFormat("bn-BD",{dateStyle:"medium",timeZone:"Asia/Dhaka"}).format(new Date(p.paid_at))}</p></article>)}</div>}</section>
</div>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-border bg-white p-5 shadow-sm"><p className="text-xs text-muted">{label}</p><p className="mt-2 text-2xl font-extrabold text-brand">{new Intl.NumberFormat("bn-BD").format(value)}</p></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-[#f7faf8] p-3"><p className="text-muted">{label}</p><p className="mt-1 font-bold uppercase">{value}</p></div>}
