import { BarChart3 } from "lucide-react";

export type DashboardTrendPoint={day:string;application_count:number|string;completed_count:number|string;service_value:number|string};
const number=new Intl.NumberFormat("bn-BD");
const money=new Intl.NumberFormat("bn-BD",{style:"currency",currency:"BDT",maximumFractionDigits:0});
const date=new Intl.DateTimeFormat("bn-BD",{day:"numeric",month:"short",timeZone:"Asia/Dhaka"});
export function DashboardTrendChart({points,title="গত ১৪ দিনের কার্যক্রম"}:{points:DashboardTrendPoint[];title?:string}){
 const rows=points.map(p=>({day:p.day,applications:Number(p.application_count),completed:Number(p.completed_count),value:Number(p.service_value)}));
 const max=Math.max(...rows.flatMap(p=>[p.applications,p.completed]),1);const total=rows.reduce((sum,p)=>sum+p.value,0);
 return <section className="rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6" aria-labelledby="dashboard-trend-title"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><BarChart3 className="size-5 text-brand"/><h2 id="dashboard-trend-title" className="text-base font-extrabold">{title}</h2></div><p className="mt-1 text-[10px] text-muted">বাংলাদেশ সময় • প্রতিদিনের আবেদন ও সম্পন্ন সেবা</p></div><div className="text-right"><p className="text-[9px] text-muted">মোট সেবা মূল্য</p><p className="text-sm font-extrabold text-brand">{money.format(total)}</p></div></div>{rows.length===0?<p className="py-12 text-center text-xs text-muted">চার্টের তথ্য পাওয়া যায়নি</p>:<><div className="mt-6 flex h-52 items-end gap-1 overflow-hidden border-b border-border" role="img" aria-label={`${rows.length} দিনের আবেদন ও সম্পন্ন সেবার বার চার্ট`}>{rows.map(p=><div key={p.day} className="group flex h-full min-w-0 flex-1 items-end justify-center gap-px" title={`${date.format(new Date(`${p.day}T00:00:00+06:00`))}: ${number.format(p.applications)} আবেদন, ${number.format(p.completed)} সম্পন্ন`}><span className="w-2/5 rounded-t-sm bg-brand" style={{height:`${Math.max((p.applications/max)*100,p.applications?4:0)}%`}}/><span className="w-2/5 rounded-t-sm bg-emerald-300" style={{height:`${Math.max((p.completed/max)*100,p.completed?4:0)}%`}}/></div>)}</div><div className="mt-2 flex justify-between text-[8px] text-muted"><span>{date.format(new Date(`${rows[0].day}T00:00:00+06:00`))}</span><span>{date.format(new Date(`${rows.at(-1)!.day}T00:00:00+06:00`))}</span></div><div className="mt-4 flex flex-wrap gap-4 text-[10px] font-semibold"><span className="flex items-center gap-1.5"><i className="size-2.5 rounded-sm bg-brand"/>আবেদন</span><span className="flex items-center gap-1.5"><i className="size-2.5 rounded-sm bg-emerald-300"/>সম্পন্ন</span></div><table className="sr-only"><caption>{title}</caption><thead><tr><th>তারিখ</th><th>আবেদন</th><th>সম্পন্ন</th><th>সেবা মূল্য</th></tr></thead><tbody>{rows.map(p=><tr key={p.day}><td>{p.day}</td><td>{p.applications}</td><td>{p.completed}</td><td>{p.value}</td></tr>)}</tbody></table></>}</section>
}
