import "server-only";
import { isSignatureStorageConfigured,testSignatureStorageConnection } from "@/lib/google-drive/signature-storage";
export type Provider="whatsapp"|"sms"|"google_drive";
export type IntegrationStatus={provider:Provider;configured:boolean;detail:string};
export function getIntegrationStatuses():IntegrationStatus[]{return[
 {provider:"whatsapp",configured:Boolean(process.env.WHATSAPP_CLOUD_API_TOKEN&&process.env.WHATSAPP_PHONE_NUMBER_ID),detail:process.env.WHATSAPP_PHONE_NUMBER_ID?`Phone ID: ••••${process.env.WHATSAPP_PHONE_NUMBER_ID.slice(-4)}`:"Cloud API credentials missing"},
 {provider:"sms",configured:Boolean(process.env.SMS_GATEWAY_URL&&process.env.SMS_GATEWAY_API_KEY&&process.env.SMS_SENDER_ID),detail:process.env.SMS_SENDER_ID?`Sender: ${process.env.SMS_SENDER_ID}`:"Gateway credentials missing"},
 {provider:"google_drive",configured:isSignatureStorageConfigured(),detail:process.env.GOOGLE_DRIVE_SIGNATURE_FOLDER_ID?`Folder: ••••${process.env.GOOGLE_DRIVE_SIGNATURE_FOLDER_ID.slice(-4)}`:"Encrypted storage credentials missing"},
]}
export async function testIntegration(provider:Provider):Promise<string>{if(provider==="google_drive"){await testSignatureStorageConnection();return"Encrypted Drive folder access verified"}if(provider==="whatsapp"){const token=process.env.WHATSAPP_CLOUD_API_TOKEN,id=process.env.WHATSAPP_PHONE_NUMBER_ID;if(!token||!id)throw new Error("WhatsApp is not configured");const version=process.env.WHATSAPP_API_VERSION??"v21.0";const r=await fetch(`https://graph.facebook.com/${version}/${encodeURIComponent(id)}?fields=id,display_phone_number,verified_name`,{headers:{authorization:`Bearer ${token}`},cache:"no-store",signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error("WhatsApp Cloud API verification failed");return"WhatsApp phone identity verified"}const url=process.env.SMS_GATEWAY_HEALTH_URL,key=process.env.SMS_GATEWAY_API_KEY;if(!process.env.SMS_GATEWAY_URL||!key||!process.env.SMS_SENDER_ID)throw new Error("SMS gateway is not configured");if(!url)return"SMS credentials present; health endpoint not configured";const r=await fetch(url,{headers:{authorization:`Bearer ${key}`},cache:"no-store",signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error("SMS gateway health check failed");return"SMS gateway health endpoint verified"}
