-- Initial fee catalogue from Appendix 6 and Appendix 7 of the project specification.
-- Before production launch, verify every amount against the gazetted 2025 guideline.

insert into public.services (code, name_bn, description_bn, sort_order) values
  ('land-tax-registration', 'ভূমি উন্নয়ন কর/ভূমিসেবা নিবন্ধন', 'ভূমি উন্নয়ন কর ব্যবস্থায় নিবন্ধন সহায়তা', 1),
  ('land-tax-payment-objection', 'ভূমি উন্নয়ন কর জমা বা আপত্তি দায়ের', 'ইউনিয়ন ভূমি অফিসের অনুমোদনের পর কর জমা বা আপত্তি', 2),
  ('dakhila-print', 'দাখিলার প্রিন্ট কপি', 'করদাতাকে দাখিলার প্রিন্ট কপি সরবরাহ', 3),
  ('e-mutation-application', 'নামজারি মামলার অনলাইন আবেদন', 'স্ক্যান পৃষ্ঠা ২০-এর বেশি হলে অতিরিক্ত পৃষ্ঠা ফি প্রযোজ্য', 4),
  ('mutation-fee-khatian-print', 'নামজারি ফি ও খতিয়ান প্রিন্ট', 'নামজারি ফি জমা এবং অনলাইন খতিয়ান প্রিন্ট', 5),
  ('khatian-porcha-application', 'খতিয়ান/পর্চার অনলাইন আবেদন', 'নামজারি বা রেকর্ডীয় খতিয়ান/পর্চার আবেদন', 6),
  ('khas-land-settlement', 'খাস কৃষি জমি বন্দোবস্ত আবেদন', 'নকশায় জমির অবস্থা প্রদর্শন ও বন্দোবস্তের আবেদন', 7),
  ('kabuliyat-submission', 'কবুলিয়ত পূরণ ও দাখিল', 'কবুলিয়ত ফরম পূরণ করে সহকারী কমিশনার (ভূমি) বরাবর দাখিল', 8),
  ('vested-property-lease', 'অর্পিত সম্পত্তি লিজ/নবায়ন', 'অর্পিত সম্পত্তির লিজ বা নবায়নের আবেদন', 9),
  ('abandoned-property-lease', 'পরিত্যক্ত সম্পত্তি লিজ/ভাড়া', 'পরিত্যক্ত সম্পত্তির লিজ বা ভাড়ার আবেদন', 10),
  ('sairat-mahal-lease', 'সায়রাত মহাল লিজ', 'সায়রাত মহাল লিজ আবেদন ও লিজ মানি জমা', 11),
  ('mouza-map', 'মৌজা ম্যাপ বা নকশা', 'আবেদন প্রস্তুত, দাখিল, ফি জমা, গ্রহণ ও বিতরণ', 12),
  ('misc-case', 'মিসকেস আবেদন', 'বিভিন্ন মিসকেস আবেদন প্রস্তুত, কাগজ আপলোড ও দাখিল', 13),
  ('other-approved-service', 'অন্যান্য অনুমোদিত অনলাইন ভূমিসেবা', 'সরকার কর্তৃক প্রদত্ত বা অনুমোদিত অন্যান্য ভূমিসেবা', 14);

insert into public.service_fees (service_code, location_type, assistance_fee, extra_page_fee) values
  ('land-tax-registration', 'union_upazila', 50, 0),
  ('land-tax-registration', 'pourashava', 50, 0),
  ('land-tax-registration', 'city_corporation_savar', 50, 0),
  ('land-tax-payment-objection', 'union_upazila', 20, 0),
  ('land-tax-payment-objection', 'pourashava', 20, 0),
  ('land-tax-payment-objection', 'city_corporation_savar', 20, 0),
  ('dakhila-print', 'union_upazila', 20, 0),
  ('dakhila-print', 'pourashava', 20, 0),
  ('dakhila-print', 'city_corporation_savar', 20, 0),
  ('e-mutation-application', 'union_upazila', 200, 3),
  ('e-mutation-application', 'pourashava', 250, 3),
  ('e-mutation-application', 'city_corporation_savar', 300, 3),
  ('mutation-fee-khatian-print', 'union_upazila', 100, 0),
  ('mutation-fee-khatian-print', 'pourashava', 100, 0),
  ('mutation-fee-khatian-print', 'city_corporation_savar', 100, 0),
  ('khatian-porcha-application', 'union_upazila', 100, 0),
  ('khatian-porcha-application', 'pourashava', 120, 0),
  ('khatian-porcha-application', 'city_corporation_savar', 150, 0),
  ('khas-land-settlement', 'union_upazila', 100, 0),
  ('khas-land-settlement', 'pourashava', 120, 0),
  ('khas-land-settlement', 'city_corporation_savar', 120, 0),
  ('kabuliyat-submission', 'union_upazila', 80, 0),
  ('kabuliyat-submission', 'pourashava', 80, 0),
  ('kabuliyat-submission', 'city_corporation_savar', 80, 0),
  ('vested-property-lease', 'union_upazila', 100, 0),
  ('vested-property-lease', 'pourashava', 120, 0),
  ('vested-property-lease', 'city_corporation_savar', 150, 0),
  ('abandoned-property-lease', 'union_upazila', 100, 0),
  ('abandoned-property-lease', 'pourashava', 120, 0),
  ('abandoned-property-lease', 'city_corporation_savar', 150, 0),
  ('sairat-mahal-lease', 'union_upazila', 100, 0),
  ('sairat-mahal-lease', 'pourashava', 120, 0),
  ('sairat-mahal-lease', 'city_corporation_savar', 150, 0),
  ('mouza-map', 'union_upazila', 100, 0),
  ('mouza-map', 'pourashava', 120, 0),
  ('mouza-map', 'city_corporation_savar', 150, 0),
  ('misc-case', 'union_upazila', 100, 0),
  ('misc-case', 'pourashava', 120, 0),
  ('misc-case', 'city_corporation_savar', 150, 0),
  ('other-approved-service', 'union_upazila', null, 0),
  ('other-approved-service', 'pourashava', null, 0),
  ('other-approved-service', 'city_corporation_savar', null, 0);

insert into public.license_fees (location_type, fee) values
  ('union_upazila', 3000),
  ('pourashava', 5000),
  ('city_corporation_savar', 8000);
