-- Phase 1 inspection readiness, complaint box, and citizen feedback.
create type public.asset_condition as enum ('operational','needs_repair','retired');
create type public.complaint_status as enum ('open','resolved');

create table public.center_assets (
 id uuid primary key default gen_random_uuid(),center_id uuid not null references public.centers(id) on delete restrict,
 asset_name text not null check(char_length(asset_name) between 2 and 120),category text not null check(char_length(category) between 2 and 80),
 serial_number text,condition public.asset_condition not null default 'operational',acquired_on date,note text,
 recorded_by uuid not null references public.profiles(id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create unique index center_asset_serial_unique on public.center_assets(center_id,serial_number) where serial_number is not null;
create trigger center_assets_set_updated_at before update on public.center_assets for each row execute function private.set_updated_at();
create table public.center_asset_history(id uuid primary key default gen_random_uuid(),asset_id uuid not null references public.center_assets(id) on delete restrict,center_id uuid not null references public.centers(id) on delete restrict,previous_condition public.asset_condition,new_condition public.asset_condition not null,note text,changed_by uuid not null references public.profiles(id) on delete restrict,changed_at timestamptz not null default now());

create table public.self_audit_inspections(id uuid primary key default gen_random_uuid(),center_id uuid not null references public.centers(id) on delete restrict,inspection_date date not null,compliant_items smallint not null,required_items smallint not null default 8,operational_assets bigint not null,notes text not null check(char_length(notes) between 10 and 1000),snapshot jsonb not null,conducted_by uuid not null references public.profiles(id) on delete restrict,created_at timestamptz not null default now(),unique(center_id,inspection_date));

create table public.center_complaints(id uuid primary key default gen_random_uuid(),center_id uuid not null references public.centers(id) on delete restrict,complaint_number text not null unique,citizen_name text,citizen_mobile text check(citizen_mobile is null or citizen_mobile ~ '^01[3-9][0-9]{8}$'),subject text not null check(char_length(subject) between 3 and 160),details text not null check(char_length(details) between 10 and 1000),status public.complaint_status not null default 'open',resolution text,resolved_at timestamptz,recorded_by uuid not null references public.profiles(id) on delete restrict,created_at timestamptz not null default now());
create table public.complaint_events(id uuid primary key default gen_random_uuid(),complaint_id uuid not null references public.center_complaints(id) on delete restrict,center_id uuid not null references public.centers(id) on delete restrict,status public.complaint_status not null,note text not null,actor_id uuid not null references public.profiles(id) on delete restrict,created_at timestamptz not null default now());

create table public.citizen_feedback(id uuid primary key default gen_random_uuid(),application_id uuid not null unique references public.applications(id) on delete restrict,center_id uuid not null references public.centers(id) on delete restrict,rating smallint not null check(rating between 1 and 5),comment text check(comment is null or char_length(comment) between 3 and 500),submitted_at timestamptz not null default now());

create or replace function private.prevent_inspection_history_mutation() returns trigger language plpgsql set search_path=pg_catalog as $$ begin raise exception 'Inspection and feedback history is immutable'; end; $$;
create trigger asset_history_immutable before update or delete on public.center_asset_history for each row execute function private.prevent_inspection_history_mutation();
create trigger self_audits_immutable before update or delete on public.self_audit_inspections for each row execute function private.prevent_inspection_history_mutation();
create trigger complaint_events_immutable before update or delete on public.complaint_events for each row execute function private.prevent_inspection_history_mutation();
create trigger citizen_feedback_immutable before update or delete on public.citizen_feedback for each row execute function private.prevent_inspection_history_mutation();

alter table public.center_assets enable row level security;alter table public.center_assets force row level security;alter table public.center_asset_history enable row level security;alter table public.center_asset_history force row level security;alter table public.self_audit_inspections enable row level security;alter table public.self_audit_inspections force row level security;alter table public.center_complaints enable row level security;alter table public.center_complaints force row level security;alter table public.complaint_events enable row level security;alter table public.complaint_events force row level security;alter table public.citizen_feedback enable row level security;alter table public.citizen_feedback force row level security;
create policy assets_owner_read on public.center_assets for select to authenticated using(private.is_super_admin() or(private.current_role()='owner' and center_id=private.current_center_id()));
create policy asset_history_owner_read on public.center_asset_history for select to authenticated using(private.is_super_admin() or(private.current_role()='owner' and center_id=private.current_center_id()));
create policy audits_owner_read on public.self_audit_inspections for select to authenticated using(private.is_super_admin() or(private.current_role()='owner' and center_id=private.current_center_id()));
create policy complaints_owner_read on public.center_complaints for select to authenticated using(private.is_super_admin() or(private.current_role()='owner' and center_id=private.current_center_id()));
create policy complaint_events_owner_read on public.complaint_events for select to authenticated using(private.is_super_admin() or(private.current_role()='owner' and center_id=private.current_center_id()));
create policy feedback_owner_read on public.citizen_feedback for select to authenticated using(private.is_super_admin() or(private.current_role()='owner' and center_id=private.current_center_id()));
create policy assets_active_gate on public.center_assets as restrictive for select to authenticated using(private.mfa_satisfied());create policy asset_history_active_gate on public.center_asset_history as restrictive for select to authenticated using(private.mfa_satisfied());create policy audits_active_gate on public.self_audit_inspections as restrictive for select to authenticated using(private.mfa_satisfied());create policy complaints_active_gate on public.center_complaints as restrictive for select to authenticated using(private.mfa_satisfied());create policy complaint_events_active_gate on public.complaint_events as restrictive for select to authenticated using(private.mfa_satisfied());create policy feedback_active_gate on public.citizen_feedback as restrictive for select to authenticated using(private.mfa_satisfied());
grant select on public.center_assets,public.center_asset_history,public.self_audit_inspections,public.center_complaints,public.complaint_events,public.citizen_feedback to authenticated;

create or replace function public.register_center_asset(p_name text,p_category text,p_serial text,p_condition public.asset_condition,p_acquired_on date,p_note text) returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare cid uuid;rid uuid;begin if private.current_role()<>'owner' or not private.mfa_satisfied() then raise exception 'Owner AAL2 required';end if;if char_length(trim(p_name)) not between 2 and 120 or char_length(trim(p_category)) not between 2 and 80 or char_length(coalesce(p_serial,''))>120 or char_length(coalesce(p_note,''))>500 then raise exception 'Invalid asset';end if;cid:=private.current_center_id();insert into public.center_assets(center_id,asset_name,category,serial_number,condition,acquired_on,note,recorded_by)values(cid,trim(p_name),trim(p_category),nullif(trim(p_serial),''),p_condition,p_acquired_on,nullif(trim(p_note),''),auth.uid())returning id into rid;insert into public.center_asset_history(asset_id,center_id,new_condition,note,changed_by)values(rid,cid,p_condition,'Asset registered',auth.uid());perform private.write_audit_log(cid,'asset.registered','center_asset',rid,jsonb_build_object('category',trim(p_category),'condition',p_condition));return rid;end;$$;
create or replace function public.update_asset_condition(p_asset_id uuid,p_condition public.asset_condition,p_note text) returns void language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare a public.center_assets%rowtype;begin if private.current_role()<>'owner' or not private.mfa_satisfied() then raise exception 'Owner AAL2 required';end if;if char_length(trim(p_note)) not between 3 and 500 then raise exception 'Note required';end if;select * into a from public.center_assets where id=p_asset_id and center_id=private.current_center_id() for update;if not found or a.condition=p_condition then raise exception 'Asset unavailable or unchanged';end if;update public.center_assets set condition=p_condition,note=trim(p_note) where id=a.id;insert into public.center_asset_history(asset_id,center_id,previous_condition,new_condition,note,changed_by)values(a.id,a.center_id,a.condition,p_condition,trim(p_note),auth.uid());perform private.write_audit_log(a.center_id,'asset.condition_changed','center_asset',a.id,jsonb_build_object('previous',a.condition,'new',p_condition));end;$$;
create or replace function public.run_center_self_audit(p_inspection_date date,p_notes text) returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare cid uuid;ok smallint;assets bigint;snap jsonb;rid uuid;begin if private.current_role()<>'owner' or not private.mfa_satisfied() then raise exception 'Owner AAL2 required';end if;if p_inspection_date>current_date or char_length(trim(p_notes)) not between 10 and 1000 then raise exception 'Invalid inspection';end if;cid:=private.current_center_id();select count(*) filter(where is_compliant) into ok from public.center_compliance_checks where center_id=cid;select count(*) filter(where condition='operational') into assets from public.center_assets where center_id=cid;select jsonb_build_object('checks',coalesce(jsonb_agg(jsonb_build_object('requirement',requirement,'compliant',is_compliant)),'[]'::jsonb),'asset_count',assets)into snap from public.center_compliance_checks where center_id=cid;insert into public.self_audit_inspections(center_id,inspection_date,compliant_items,operational_assets,notes,snapshot,conducted_by)values(cid,p_inspection_date,ok,assets,trim(p_notes),snap,auth.uid())returning id into rid;perform private.write_audit_log(cid,'inspection.self_audit_completed','self_audit',rid,jsonb_build_object('compliant_items',ok,'operational_assets',assets));return rid;exception when unique_violation then raise exception 'Inspection already exists for this date';end;$$;
create or replace function public.record_center_complaint(p_name text,p_mobile text,p_subject text,p_details text) returns text language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare cid uuid;rid uuid;num text;begin if private.current_role()<>'owner' or not private.mfa_satisfied() then raise exception 'Owner AAL2 required';end if;if char_length(trim(p_subject)) not between 3 and 160 or char_length(trim(p_details)) not between 10 and 1000 or(p_mobile is not null and p_mobile!~'^01[3-9][0-9]{8}$')then raise exception 'Invalid complaint';end if;cid:=private.current_center_id();num:='CMP-'||to_char(clock_timestamp(),'YYYYMMDD')||'-'||upper(encode(gen_random_bytes(5),'hex'));insert into public.center_complaints(center_id,complaint_number,citizen_name,citizen_mobile,subject,details,recorded_by)values(cid,num,nullif(trim(p_name),''),nullif(trim(p_mobile),''),trim(p_subject),trim(p_details),auth.uid())returning id into rid;insert into public.complaint_events(complaint_id,center_id,status,note,actor_id)values(rid,cid,'open','Complaint recorded',auth.uid());perform private.write_audit_log(cid,'complaint.recorded','center_complaint',rid,jsonb_build_object('complaint_number',num));return num;end;$$;
create or replace function public.resolve_center_complaint(p_complaint_id uuid,p_resolution text) returns void language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare c public.center_complaints%rowtype;begin if private.current_role()<>'owner' or not private.mfa_satisfied() then raise exception 'Owner AAL2 required';end if;if char_length(trim(p_resolution)) not between 10 and 1000 then raise exception 'Resolution required';end if;select * into c from public.center_complaints where id=p_complaint_id and center_id=private.current_center_id() for update;if not found or c.status<>'open'then raise exception 'Open complaint not found';end if;update public.center_complaints set status='resolved',resolution=trim(p_resolution),resolved_at=now() where id=c.id;insert into public.complaint_events(complaint_id,center_id,status,note,actor_id)values(c.id,c.center_id,'resolved',trim(p_resolution),auth.uid());perform private.write_audit_log(c.center_id,'complaint.resolved','center_complaint',c.id,jsonb_build_object('complaint_number',c.complaint_number));end;$$;
create or replace function public.submit_citizen_feedback(p_tracking_id text,p_mobile text,p_rating integer,p_comment text)returns void language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare a public.applications%rowtype;begin if p_mobile!~'^01[3-9][0-9]{8}$'or p_rating not between 1 and 5 or char_length(coalesce(p_comment,''))>500 then raise exception 'Invalid feedback';end if;select * into a from public.applications where tracking_id=upper(trim(p_tracking_id))and citizen_mobile=p_mobile and status='completed';if not found then raise exception 'Completed application not found';end if;insert into public.citizen_feedback(application_id,center_id,rating,comment)values(a.id,a.center_id,p_rating,nullif(trim(p_comment),''));exception when unique_violation then raise exception 'Feedback already submitted';end;$$;

revoke execute on function public.register_center_asset(text,text,text,public.asset_condition,date,text),public.update_asset_condition(uuid,public.asset_condition,text),public.run_center_self_audit(date,text),public.record_center_complaint(text,text,text,text),public.resolve_center_complaint(uuid,text) from public,anon;grant execute on function public.register_center_asset(text,text,text,public.asset_condition,date,text),public.update_asset_condition(uuid,public.asset_condition,text),public.run_center_self_audit(date,text),public.record_center_complaint(text,text,text,text),public.resolve_center_complaint(uuid,text) to authenticated;revoke execute on function public.submit_citizen_feedback(text,text,integer,text) from public;grant execute on function public.submit_citizen_feedback(text,text,integer,text) to anon,authenticated;revoke all on function private.prevent_inspection_history_mutation() from public,anon,authenticated;
