-- Phase 1 dynamic public CMS and central notice board.
create type public.publication_status as enum ('draft','published','archived');
create type public.notice_audience as enum ('all_users','owners','operators','public');

create table public.cms_pages(id uuid primary key default gen_random_uuid(),slug text not null unique check(slug~'^[a-z0-9-]{2,60}$'),title text not null check(char_length(title) between 2 and 160),content text not null check(char_length(content) between 10 and 50000),status public.publication_status not null default 'draft',version integer not null default 1,created_by uuid not null references public.profiles(id) on delete restrict,updated_by uuid not null references public.profiles(id) on delete restrict,published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create trigger cms_pages_set_updated_at before update on public.cms_pages for each row execute function private.set_updated_at();
create table public.cms_page_versions(id uuid primary key default gen_random_uuid(),page_id uuid not null references public.cms_pages(id) on delete restrict,version integer not null,title text not null,content text not null,status public.publication_status not null,changed_by uuid not null references public.profiles(id) on delete restrict,created_at timestamptz not null default now(),unique(page_id,version));

create table public.central_notices(id uuid primary key default gen_random_uuid(),title text not null check(char_length(title) between 3 and 160),body text not null check(char_length(body) between 10 and 5000),audience public.notice_audience not null,status public.publication_status not null default 'draft',priority smallint not null default 0 check(priority between 0 and 3),starts_at timestamptz,ends_at timestamptz,version integer not null default 1,created_by uuid not null references public.profiles(id) on delete restrict,updated_by uuid not null references public.profiles(id) on delete restrict,published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at is null or starts_at is null or ends_at>starts_at));
create trigger central_notices_set_updated_at before update on public.central_notices for each row execute function private.set_updated_at();
create table public.central_notice_versions(id uuid primary key default gen_random_uuid(),notice_id uuid not null references public.central_notices(id) on delete restrict,version integer not null,title text not null,body text not null,audience public.notice_audience not null,status public.publication_status not null,priority smallint not null,changed_by uuid not null references public.profiles(id) on delete restrict,created_at timestamptz not null default now(),unique(notice_id,version));

create or replace function private.prevent_publication_history_mutation()returns trigger language plpgsql set search_path=pg_catalog as $$begin raise exception 'Publication history is immutable';end;$$;
create trigger cms_versions_immutable before update or delete on public.cms_page_versions for each row execute function private.prevent_publication_history_mutation();
create trigger notice_versions_immutable before update or delete on public.central_notice_versions for each row execute function private.prevent_publication_history_mutation();

alter table public.cms_pages enable row level security;alter table public.cms_pages force row level security;alter table public.cms_page_versions enable row level security;alter table public.cms_page_versions force row level security;alter table public.central_notices enable row level security;alter table public.central_notices force row level security;alter table public.central_notice_versions enable row level security;alter table public.central_notice_versions force row level security;
create policy cms_public_read on public.cms_pages for select to anon,authenticated using(status='published' or private.is_super_admin());
create policy cms_versions_super_read on public.cms_page_versions for select to authenticated using(private.is_super_admin() and private.mfa_satisfied());
create policy notices_public_read on public.central_notices for select to anon using(status='published' and audience='public' and (starts_at is null or starts_at<=now())and(ends_at is null or ends_at>now()));
create policy notices_authenticated_read on public.central_notices for select to authenticated using(private.is_super_admin()or(status='published'and(starts_at is null or starts_at<=now())and(ends_at is null or ends_at>now())and(audience='all_users'or audience='public'or(audience='owners'and private.current_role()='owner')or(audience='operators'and private.current_role()='operator'))));
create policy notice_versions_super_read on public.central_notice_versions for select to authenticated using(private.is_super_admin()and private.mfa_satisfied());
grant select on public.cms_pages,public.central_notices to anon,authenticated;grant select on public.cms_page_versions,public.central_notice_versions to authenticated;

create or replace function public.save_cms_page(p_slug text,p_title text,p_content text,p_publish boolean)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare page public.cms_pages%rowtype;rid uuid;new_status public.publication_status;begin if not private.is_super_admin()or not private.mfa_satisfied()then raise exception 'Super Admin AAL2 required';end if;if trim(p_slug)!~'^[a-z0-9-]{2,60}$'or char_length(trim(p_title))not between 2 and 160 or char_length(trim(p_content))not between 10 and 50000 then raise exception 'Invalid page';end if;new_status:=case when p_publish then 'published'::public.publication_status else 'draft'::public.publication_status end;select * into page from public.cms_pages where slug=trim(p_slug)for update;if found then update public.cms_pages set title=trim(p_title),content=trim(p_content),status=new_status,version=page.version+1,updated_by=auth.uid(),published_at=case when p_publish then now()else page.published_at end where id=page.id returning id into rid;insert into public.cms_page_versions(page_id,version,title,content,status,changed_by)values(page.id,page.version+1,trim(p_title),trim(p_content),new_status,auth.uid());else insert into public.cms_pages(slug,title,content,status,created_by,updated_by,published_at)values(trim(p_slug),trim(p_title),trim(p_content),new_status,auth.uid(),auth.uid(),case when p_publish then now()end)returning id into rid;insert into public.cms_page_versions(page_id,version,title,content,status,changed_by)values(rid,1,trim(p_title),trim(p_content),new_status,auth.uid());end if;perform private.write_audit_log(null,'cms.page_saved','cms_page',rid,jsonb_build_object('slug',trim(p_slug),'status',new_status));return rid;end;$$;
create or replace function public.save_central_notice(p_notice_id uuid,p_title text,p_body text,p_audience public.notice_audience,p_priority integer,p_starts_at timestamptz,p_ends_at timestamptz,p_publish boolean)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare n public.central_notices%rowtype;rid uuid;new_status public.publication_status;begin if not private.is_super_admin()or not private.mfa_satisfied()then raise exception 'Super Admin AAL2 required';end if;if char_length(trim(p_title))not between 3 and 160 or char_length(trim(p_body))not between 10 and 5000 or p_priority not between 0 and 3 or(p_starts_at is not null and p_ends_at is not null and p_ends_at<=p_starts_at)then raise exception 'Invalid notice';end if;new_status:=case when p_publish then 'published'::public.publication_status else 'draft'::public.publication_status end;if p_notice_id is not null then select * into n from public.central_notices where id=p_notice_id for update;if not found then raise exception 'Notice not found';end if;update public.central_notices set title=trim(p_title),body=trim(p_body),audience=p_audience,priority=p_priority,starts_at=p_starts_at,ends_at=p_ends_at,status=new_status,version=n.version+1,updated_by=auth.uid(),published_at=case when p_publish then now()else n.published_at end where id=n.id returning id into rid;insert into public.central_notice_versions(notice_id,version,title,body,audience,status,priority,changed_by)values(n.id,n.version+1,trim(p_title),trim(p_body),p_audience,new_status,p_priority,auth.uid());else insert into public.central_notices(title,body,audience,status,priority,starts_at,ends_at,created_by,updated_by,published_at)values(trim(p_title),trim(p_body),p_audience,new_status,p_priority,p_starts_at,p_ends_at,auth.uid(),auth.uid(),case when p_publish then now()end)returning id into rid;insert into public.central_notice_versions(notice_id,version,title,body,audience,status,priority,changed_by)values(rid,1,trim(p_title),trim(p_body),p_audience,new_status,p_priority,auth.uid());end if;perform private.write_audit_log(null,'notice.saved','central_notice',rid,jsonb_build_object('audience',p_audience,'status',new_status,'priority',p_priority));return rid;end;$$;
revoke execute on function public.save_cms_page(text,text,text,boolean),public.save_central_notice(uuid,text,text,public.notice_audience,integer,timestamptz,timestamptz,boolean)from public,anon;grant execute on function public.save_cms_page(text,text,text,boolean),public.save_central_notice(uuid,text,text,public.notice_audience,integer,timestamptz,timestamptz,boolean)to authenticated;revoke all on function private.prevent_publication_history_mutation()from public,anon,authenticated;
