-- Phase 1 secure external-integration administration.
-- Credentials remain in server environment variables; only test outcomes are stored.
create type public.integration_provider as enum ('whatsapp','sms','google_drive');
create table public.integration_health_checks(id uuid primary key default gen_random_uuid(),provider public.integration_provider not null,succeeded boolean not null,message text not null check(char_length(message) between 2 and 500),latency_ms integer check(latency_ms is null or latency_ms>=0),checked_by uuid not null references public.profiles(id) on delete restrict,checked_at timestamptz not null default now());
create index integration_health_provider_checked_idx on public.integration_health_checks(provider,checked_at desc);
create or replace function private.prevent_integration_health_mutation()returns trigger language plpgsql set search_path=pg_catalog as $$begin raise exception 'Integration health history is immutable';end;$$;
create trigger integration_health_immutable before update or delete on public.integration_health_checks for each row execute function private.prevent_integration_health_mutation();
alter table public.integration_health_checks enable row level security;alter table public.integration_health_checks force row level security;
create policy integration_health_super_read on public.integration_health_checks for select to authenticated using(private.is_super_admin()and private.mfa_satisfied());grant select on public.integration_health_checks to authenticated;
create or replace function public.record_integration_health(p_provider public.integration_provider,p_succeeded boolean,p_message text,p_latency_ms integer)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare rid uuid;begin if not private.is_super_admin()or not private.mfa_satisfied()then raise exception 'Super Admin AAL2 required';end if;if char_length(trim(p_message))not between 2 and 500 or p_latency_ms<0 then raise exception 'Invalid health result';end if;insert into public.integration_health_checks(provider,succeeded,message,latency_ms,checked_by)values(p_provider,p_succeeded,trim(p_message),p_latency_ms,auth.uid())returning id into rid;perform private.write_audit_log(null,'integration.health_checked','integration',rid,jsonb_build_object('provider',p_provider,'succeeded',p_succeeded,'latency_ms',p_latency_ms));return rid;end;$$;
revoke execute on function public.record_integration_health(public.integration_provider,boolean,text,integer)from public,anon;grant execute on function public.record_integration_health(public.integration_provider,boolean,text,integer)to authenticated;revoke all on function private.prevent_integration_health_mutation()from public,anon,authenticated;
