-- Center-scoped Owner-to-staff notices with immutable revision history.
create table public.center_notices(
 id uuid primary key default gen_random_uuid(),center_id uuid not null references public.centers(id),title text not null check(char_length(title)between 3 and 160),body text not null check(char_length(body)between 10 and 5000),status public.publication_status not null default'draft',priority smallint not null default 0 check(priority between 0 and 3),starts_at timestamptz,ends_at timestamptz,version integer not null default 1,created_by uuid not null references public.profiles(id),updated_by uuid not null references public.profiles(id),published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at is null or starts_at is null or ends_at>starts_at)
);
create table public.center_notice_versions(
 id uuid primary key default gen_random_uuid(),notice_id uuid not null references public.center_notices(id),center_id uuid not null references public.centers(id),version integer not null,title text not null,body text not null,status public.publication_status not null,priority smallint not null,changed_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),unique(notice_id,version)
);
create index center_notices_center_time_idx on public.center_notices(center_id,created_at desc);create index center_notice_versions_notice_idx on public.center_notice_versions(notice_id,version desc);
create trigger center_notices_set_updated_at before update on public.center_notices for each row execute function private.set_updated_at();create trigger center_notice_versions_immutable before update or delete on public.center_notice_versions for each row execute function private.prevent_publication_history_mutation();
alter table public.center_notices enable row level security;alter table public.center_notices force row level security;alter table public.center_notice_versions enable row level security;alter table public.center_notice_versions force row level security;
create policy center_notices_owner_read on public.center_notices for select to authenticated using(center_id=private.current_center_id()and private.current_role()='owner'and private.mfa_satisfied());
create policy center_notices_operator_read on public.center_notices for select to authenticated using(center_id=private.current_center_id()and private.current_role()='operator'and private.mfa_satisfied()and status='published'and(starts_at is null or starts_at<=now())and(ends_at is null or ends_at>now()));
create policy center_notices_super_read on public.center_notices for select to authenticated using(private.is_super_admin()and private.mfa_satisfied());
create policy center_notice_versions_owner_read on public.center_notice_versions for select to authenticated using(center_id=private.current_center_id()and private.current_role()='owner'and private.mfa_satisfied());
create policy center_notice_versions_super_read on public.center_notice_versions for select to authenticated using(private.is_super_admin()and private.mfa_satisfied());
revoke all on public.center_notices,public.center_notice_versions from anon,authenticated;grant select on public.center_notices,public.center_notice_versions to authenticated;
create or replace function public.save_center_notice(p_notice_id uuid,p_title text,p_body text,p_priority integer,p_starts_at timestamptz,p_ends_at timestamptz,p_publish boolean)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare n public.center_notices%rowtype;rid uuid;cid uuid;new_status public.publication_status;begin
 if private.current_role()<>'owner'or not private.mfa_satisfied()then raise exception'Owner AAL2 required';end if;cid:=private.current_center_id();if cid is null or not exists(select 1 from public.centers where id=cid and status='active')then raise exception'Active center required';end if;
 if char_length(trim(p_title))not between 3 and 160 or char_length(trim(p_body))not between 10 and 5000 or p_priority not between 0 and 3 or(p_starts_at is not null and p_ends_at is not null and p_ends_at<=p_starts_at)then raise exception'Invalid notice';end if;new_status:=case when p_publish then'published'::public.publication_status else'draft'::public.publication_status end;
 if p_notice_id is not null then select*into n from public.center_notices where id=p_notice_id and center_id=cid for update;if not found then raise exception'Notice not found';end if;update public.center_notices set title=trim(p_title),body=trim(p_body),priority=p_priority,starts_at=p_starts_at,ends_at=p_ends_at,status=new_status,version=n.version+1,updated_by=auth.uid(),published_at=case when p_publish then coalesce(n.published_at,now())else n.published_at end where id=n.id returning id into rid;insert into public.center_notice_versions(notice_id,center_id,version,title,body,status,priority,changed_by)values(n.id,cid,n.version+1,trim(p_title),trim(p_body),new_status,p_priority,auth.uid());
 else insert into public.center_notices(center_id,title,body,status,priority,starts_at,ends_at,created_by,updated_by,published_at)values(cid,trim(p_title),trim(p_body),new_status,p_priority,p_starts_at,p_ends_at,auth.uid(),auth.uid(),case when p_publish then now()end)returning id into rid;insert into public.center_notice_versions(notice_id,center_id,version,title,body,status,priority,changed_by)values(rid,cid,1,trim(p_title),trim(p_body),new_status,p_priority,auth.uid());end if;
 perform private.write_audit_log(cid,'center_notice.saved','center_notice',rid,jsonb_build_object('status',new_status,'priority',p_priority));return rid;
end;$$;
revoke execute on function public.save_center_notice(uuid,text,text,integer,timestamptz,timestamptz,boolean)from public,anon;grant execute on function public.save_center_notice(uuid,text,text,integer,timestamptz,timestamptz,boolean)to authenticated;
