-- Encrypted application-document metadata; file bytes remain private in Google Drive.
create table public.application_documents(
 id uuid primary key default gen_random_uuid(),application_id uuid not null references public.applications(id),center_id uuid not null references public.centers(id),service_code text not null references public.services(code),document_type text not null check(document_type in('nid','khatian','map','application','supporting','other')),drive_file_id text not null unique check(char_length(drive_file_id)between 10 and 255),encrypted_file_name text not null check(encrypted_file_name~'^enc_[a-f0-9]{24}\.bin$'),file_hash text not null check(file_hash~'^[a-f0-9]{64}$'),mime_type text not null check(mime_type in('application/pdf','image/png','image/jpeg','image/webp')),plain_size integer not null check(plain_size between 1 and 10485760),encrypted_size integer not null check(encrypted_size>plain_size and encrypted_size<=10485824),drive_path_key text not null check(char_length(drive_path_key)between 10 and 500),created_by uuid not null references public.profiles(id),created_at timestamptz not null default now()
);
create index application_documents_app_idx on public.application_documents(application_id,created_at desc);create index application_documents_center_idx on public.application_documents(center_id,created_at desc);
alter table public.application_documents enable row level security;alter table public.application_documents force row level security;
create policy application_documents_tenant_read on public.application_documents for select to authenticated using(private.is_center_manager(center_id)or(center_id=private.current_center_id()and private.current_role()='operator'and private.mfa_satisfied()));
revoke all on public.application_documents from anon,authenticated;grant select on public.application_documents to authenticated;
create trigger application_documents_immutable before update or delete on public.application_documents for each row execute function private.prevent_receipt_mutation();
create or replace function public.register_application_document(p_application_id uuid,p_document_type text,p_drive_file_id text,p_encrypted_file_name text,p_file_hash text,p_mime_type text,p_plain_size integer,p_encrypted_size integer,p_drive_path_key text)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare app public.applications%rowtype;rid uuid;begin
 if private.current_role()<>'operator'or not private.mfa_satisfied()or not private.operator_has_permission('application.create')then raise exception'Operator document permission required';end if;
 select a.*into app from public.applications a join public.centers c on c.id=a.center_id where a.id=p_application_id and a.center_id=private.current_center_id()and c.status='active';if not found then raise exception'Application not found';end if;
 if p_document_type not in('nid','khatian','map','application','supporting','other')or char_length(p_drive_file_id)not between 10 and 255 or p_encrypted_file_name!~'^enc_[a-f0-9]{24}\.bin$'or p_file_hash!~'^[a-f0-9]{64}$'or p_mime_type not in('application/pdf','image/png','image/jpeg','image/webp')or p_plain_size not between 1 and 10485760 or p_encrypted_size<=p_plain_size or p_encrypted_size>10485824 or char_length(p_drive_path_key)not between 10 and 500 then raise exception'Invalid document metadata';end if;
 insert into public.application_documents(application_id,center_id,service_code,document_type,drive_file_id,encrypted_file_name,file_hash,mime_type,plain_size,encrypted_size,drive_path_key,created_by)values(app.id,app.center_id,app.service_code,p_document_type,p_drive_file_id,p_encrypted_file_name,p_file_hash,p_mime_type,p_plain_size,p_encrypted_size,p_drive_path_key,auth.uid())returning id into rid;
 perform private.write_audit_log(app.center_id,'application.document_registered','application_document',rid,jsonb_build_object('application_id',app.id,'document_type',p_document_type,'file_hash',p_file_hash,'plain_size',p_plain_size));return rid;
end;$$;
revoke execute on function public.register_application_document(uuid,text,text,text,text,text,integer,integer,text)from public,anon;grant execute on function public.register_application_document(uuid,text,text,text,text,text,integer,integer,text)to authenticated;
comment on table public.application_documents is 'Immutable metadata for AES-256-GCM files stored under Center/Year/Month/Service Drive folders.';
