-- Staff biodata foundation and append-only attendance/performance records.
create table public.staff_biodata(
 profile_id uuid primary key references public.profiles(id),center_id uuid not null references public.centers(id),date_of_birth date,address text check(address is null or char_length(address)between 5 and 500),emergency_contact_name text check(emergency_contact_name is null or char_length(emergency_contact_name)between 2 and 120),emergency_contact_phone text check(emergency_contact_phone is null or emergency_contact_phone~'^01[3-9][0-9]{8}$'),education text check(education is null or char_length(education)between 2 and 300),notes text check(notes is null or char_length(notes)<=1000),updated_by uuid not null references public.profiles(id),updated_at timestamptz not null default now()
);
create type public.attendance_status as enum('present','absent','leave','remote');
create table public.staff_attendance_events(
 id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id),center_id uuid not null references public.centers(id),attendance_date date not null,status public.attendance_status not null,check_in time,check_out time,note text check(note is null or char_length(note)<=500),recorded_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),check(check_out is null or check_in is null or check_out>=check_in)
);
create table public.staff_performance_reviews(
 id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id),center_id uuid not null references public.centers(id),period_start date not null,period_end date not null,rating smallint not null check(rating between 1 and 5),summary text not null check(char_length(summary)between 10 and 2000),recorded_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),check(period_end>=period_start)
);
create index staff_attendance_profile_date_idx on public.staff_attendance_events(profile_id,attendance_date desc,created_at desc);create index staff_performance_profile_period_idx on public.staff_performance_reviews(profile_id,period_end desc);
create trigger staff_biodata_set_updated_at before update on public.staff_biodata for each row execute function private.set_updated_at();create trigger staff_attendance_immutable before update or delete on public.staff_attendance_events for each row execute function private.prevent_revision_mutation();create trigger staff_performance_immutable before update or delete on public.staff_performance_reviews for each row execute function private.prevent_revision_mutation();
alter table public.staff_biodata enable row level security;alter table public.staff_biodata force row level security;alter table public.staff_attendance_events enable row level security;alter table public.staff_attendance_events force row level security;alter table public.staff_performance_reviews enable row level security;alter table public.staff_performance_reviews force row level security;
create policy staff_biodata_manager_read on public.staff_biodata for select to authenticated using(private.is_center_manager(center_id)and private.mfa_satisfied());create policy staff_biodata_self_read on public.staff_biodata for select to authenticated using(profile_id=auth.uid()and center_id=private.current_center_id()and private.mfa_satisfied());
create policy staff_attendance_manager_read on public.staff_attendance_events for select to authenticated using(private.is_center_manager(center_id)and private.mfa_satisfied());create policy staff_attendance_self_read on public.staff_attendance_events for select to authenticated using(profile_id=auth.uid()and center_id=private.current_center_id()and private.mfa_satisfied());
create policy staff_performance_manager_read on public.staff_performance_reviews for select to authenticated using(private.is_center_manager(center_id)and private.mfa_satisfied());create policy staff_performance_self_read on public.staff_performance_reviews for select to authenticated using(profile_id=auth.uid()and center_id=private.current_center_id()and private.mfa_satisfied());
revoke all on public.staff_biodata,public.staff_attendance_events,public.staff_performance_reviews from anon,authenticated;grant select on public.staff_biodata,public.staff_attendance_events,public.staff_performance_reviews to authenticated;

create or replace function private.assert_owned_operator(p_profile_id uuid)returns uuid language plpgsql stable security definer set search_path=pg_catalog,public,private as $$declare cid uuid;begin if private.current_role()<>'owner'or not private.mfa_satisfied()then raise exception'Owner AAL2 required';end if;cid:=private.current_center_id();if not exists(select 1 from public.profiles where id=p_profile_id and center_id=cid and role='operator')then raise exception'Operator not found';end if;return cid;end;$$;
create or replace function public.save_staff_biodata(p_profile_id uuid,p_date_of_birth date,p_address text,p_emergency_contact_name text,p_emergency_contact_phone text,p_education text,p_notes text)returns void language plpgsql security definer set search_path=pg_catalog,public,private as $$declare cid uuid;begin cid:=private.assert_owned_operator(p_profile_id);if p_date_of_birth is not null and(p_date_of_birth>current_date-interval'16 years'or p_date_of_birth<date'1940-01-01')then raise exception'Invalid date of birth';end if;insert into public.staff_biodata(profile_id,center_id,date_of_birth,address,emergency_contact_name,emergency_contact_phone,education,notes,updated_by)values(p_profile_id,cid,p_date_of_birth,nullif(trim(p_address),''),nullif(trim(p_emergency_contact_name),''),nullif(trim(p_emergency_contact_phone),''),nullif(trim(p_education),''),nullif(trim(p_notes),''),auth.uid())on conflict(profile_id)do update set date_of_birth=excluded.date_of_birth,address=excluded.address,emergency_contact_name=excluded.emergency_contact_name,emergency_contact_phone=excluded.emergency_contact_phone,education=excluded.education,notes=excluded.notes,updated_by=auth.uid();perform private.write_audit_log(cid,'staff.biodata_updated','profile',p_profile_id,'{}'::jsonb);end;$$;
create or replace function public.record_staff_attendance(p_profile_id uuid,p_date date,p_status public.attendance_status,p_check_in time,p_check_out time,p_note text)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare cid uuid;rid uuid;begin cid:=private.assert_owned_operator(p_profile_id);if p_date is null or p_date>current_date+1 or p_date<current_date-interval'1 year'or(p_check_in is not null and p_check_out is not null and p_check_out<p_check_in)then raise exception'Invalid attendance';end if;insert into public.staff_attendance_events(profile_id,center_id,attendance_date,status,check_in,check_out,note,recorded_by)values(p_profile_id,cid,p_date,p_status,p_check_in,p_check_out,nullif(trim(p_note),''),auth.uid())returning id into rid;perform private.write_audit_log(cid,'staff.attendance_recorded','staff_attendance',rid,jsonb_build_object('profile_id',p_profile_id,'date',p_date,'status',p_status));return rid;end;$$;
create or replace function public.record_staff_performance(p_profile_id uuid,p_period_start date,p_period_end date,p_rating integer,p_summary text)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare cid uuid;rid uuid;begin cid:=private.assert_owned_operator(p_profile_id);if p_period_start is null or p_period_end is null or p_period_end<p_period_start or p_period_end>current_date+1 or p_rating not between 1 and 5 or char_length(trim(p_summary))not between 10 and 2000 then raise exception'Invalid review';end if;insert into public.staff_performance_reviews(profile_id,center_id,period_start,period_end,rating,summary,recorded_by)values(p_profile_id,cid,p_period_start,p_period_end,p_rating,trim(p_summary),auth.uid())returning id into rid;perform private.write_audit_log(cid,'staff.performance_recorded','staff_performance',rid,jsonb_build_object('profile_id',p_profile_id,'period_start',p_period_start,'period_end',p_period_end,'rating',p_rating));return rid;end;$$;
revoke all on function private.assert_owned_operator(uuid)from public,anon,authenticated;revoke execute on function public.save_staff_biodata(uuid,date,text,text,text,text,text),public.record_staff_attendance(uuid,date,public.attendance_status,time,time,text),public.record_staff_performance(uuid,date,date,integer,text)from public,anon;grant execute on function public.save_staff_biodata(uuid,date,text,text,text,text,text),public.record_staff_attendance(uuid,date,public.attendance_status,time,time,text),public.record_staff_performance(uuid,date,date,integer,text)to authenticated;
