-- Immutable encrypted Center-logo versions for receipt branding.
create table public.center_brand_assets(
 id uuid primary key default gen_random_uuid(),center_id uuid not null references public.centers(id),asset_type text not null check(asset_type='logo'),drive_file_id text not null unique check(char_length(drive_file_id)between 10 and 255),encrypted_file_name text not null check(encrypted_file_name~'^enc_[a-f0-9]{24}\.bin$'),file_hash text not null check(file_hash~'^[a-f0-9]{64}$'),mime_type text not null check(mime_type in('image/png','image/jpeg','image/webp')),plain_size integer not null check(plain_size between 1 and 2097152),encrypted_size integer not null check(encrypted_size>plain_size and encrypted_size<=2097216),drive_path_key text not null check(char_length(drive_path_key)between 10 and 500),created_by uuid not null references public.profiles(id),created_at timestamptz not null default now()
);
create index center_brand_assets_latest_idx on public.center_brand_assets(center_id,asset_type,created_at desc);
alter table public.center_brand_assets enable row level security;alter table public.center_brand_assets force row level security;
create policy center_brand_assets_tenant_read on public.center_brand_assets for select to authenticated using(private.is_center_manager(center_id)or(center_id=private.current_center_id()and private.current_role()='operator'and private.mfa_satisfied()));
revoke all on public.center_brand_assets from anon,authenticated;grant select on public.center_brand_assets to authenticated;
create trigger center_brand_assets_immutable before update or delete on public.center_brand_assets for each row execute function private.prevent_receipt_mutation();
create or replace function public.register_center_logo(p_drive_file_id text,p_encrypted_file_name text,p_file_hash text,p_mime_type text,p_plain_size integer,p_encrypted_size integer,p_drive_path_key text)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare cid uuid;rid uuid;begin
 if private.current_role()<>'owner'or not private.mfa_satisfied()then raise exception'Owner AAL2 required';end if;cid:=private.current_center_id();if cid is null or not exists(select 1 from public.centers where id=cid and status='active')then raise exception'Active Center required';end if;
 if char_length(p_drive_file_id)not between 10 and 255 or p_encrypted_file_name!~'^enc_[a-f0-9]{24}\.bin$'or p_file_hash!~'^[a-f0-9]{64}$'or p_mime_type not in('image/png','image/jpeg','image/webp')or p_plain_size not between 1 and 2097152 or p_encrypted_size<=p_plain_size or p_encrypted_size>2097216 or char_length(p_drive_path_key)not between 10 and 500 then raise exception'Invalid Center logo metadata';end if;
 insert into public.center_brand_assets(center_id,asset_type,drive_file_id,encrypted_file_name,file_hash,mime_type,plain_size,encrypted_size,drive_path_key,created_by)values(cid,'logo',p_drive_file_id,p_encrypted_file_name,p_file_hash,p_mime_type,p_plain_size,p_encrypted_size,p_drive_path_key,auth.uid())returning id into rid;
 perform private.write_audit_log(cid,'center.logo_registered','center_brand_asset',rid,jsonb_build_object('file_hash',p_file_hash,'plain_size',p_plain_size));return rid;
end;$$;
revoke execute on function public.register_center_logo(text,text,text,text,integer,integer,text)from public,anon;grant execute on function public.register_center_logo(text,text,text,text,integer,integer,text)to authenticated;
comment on table public.center_brand_assets is'Append-only metadata for encrypted Center receipt-logo versions.';
