-- Encrypted, append-only license and renewal evidence for Owner submission and Super Admin review.
create table public.license_evidence_documents(
 id uuid primary key default gen_random_uuid(),center_id uuid not null references public.centers(id),renewal_request_id uuid references public.license_renewal_requests(id),document_type text not null check(document_type in('form_2','dc_letter','current_license')),drive_file_id text not null unique check(char_length(drive_file_id)between 10 and 255),encrypted_file_name text not null check(encrypted_file_name~'^enc_[a-f0-9]{24}\.bin$'),file_hash text not null check(file_hash~'^[a-f0-9]{64}$'),mime_type text not null check(mime_type in('application/pdf','image/png','image/jpeg','image/webp')),plain_size integer not null check(plain_size between 1 and 10485760),encrypted_size integer not null check(encrypted_size>plain_size and encrypted_size<=10485824),drive_path_key text not null check(char_length(drive_path_key)between 10 and 500),created_by uuid not null references public.profiles(id),created_at timestamptz not null default now()
);
create index license_evidence_center_idx on public.license_evidence_documents(center_id,created_at desc);create index license_evidence_request_idx on public.license_evidence_documents(renewal_request_id,created_at desc)where renewal_request_id is not null;
alter table public.license_evidence_documents enable row level security;alter table public.license_evidence_documents force row level security;
create policy license_evidence_review_read on public.license_evidence_documents for select to authenticated using(private.is_super_admin()or(private.current_role()='owner'and center_id=private.current_center_id()and private.mfa_satisfied()));
revoke all on public.license_evidence_documents from anon,authenticated;grant select on public.license_evidence_documents to authenticated;
create trigger license_evidence_immutable before update or delete on public.license_evidence_documents for each row execute function private.prevent_receipt_mutation();
create or replace function public.register_license_evidence(p_renewal_request_id uuid,p_document_type text,p_drive_file_id text,p_encrypted_file_name text,p_file_hash text,p_mime_type text,p_plain_size integer,p_encrypted_size integer,p_drive_path_key text)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare cid uuid;rid uuid;begin
 if private.current_role()<>'owner'or not private.mfa_satisfied()then raise exception'Owner AAL2 required';end if;cid:=private.current_center_id();if cid is null or not exists(select 1 from public.centers where id=cid and status='active')then raise exception'Active Center required';end if;
 if p_renewal_request_id is not null and not exists(select 1 from public.license_renewal_requests r where r.id=p_renewal_request_id and r.center_id=cid and r.status='pending')then raise exception'Pending renewal request not found';end if;
 if p_document_type not in('form_2','dc_letter','current_license')or char_length(p_drive_file_id)not between 10 and 255 or p_encrypted_file_name!~'^enc_[a-f0-9]{24}\.bin$'or p_file_hash!~'^[a-f0-9]{64}$'or p_mime_type not in('application/pdf','image/png','image/jpeg','image/webp')or p_plain_size not between 1 and 10485760 or p_encrypted_size<=p_plain_size or p_encrypted_size>10485824 or char_length(p_drive_path_key)not between 10 and 500 then raise exception'Invalid license evidence metadata';end if;
 insert into public.license_evidence_documents(center_id,renewal_request_id,document_type,drive_file_id,encrypted_file_name,file_hash,mime_type,plain_size,encrypted_size,drive_path_key,created_by)values(cid,p_renewal_request_id,p_document_type,p_drive_file_id,p_encrypted_file_name,p_file_hash,p_mime_type,p_plain_size,p_encrypted_size,p_drive_path_key,auth.uid())returning id into rid;
 perform private.write_audit_log(cid,'license.evidence_registered','license_evidence',rid,jsonb_build_object('renewal_request_id',p_renewal_request_id,'document_type',p_document_type,'file_hash',p_file_hash));return rid;
end;$$;
revoke execute on function public.register_license_evidence(uuid,text,text,text,text,text,integer,integer,text)from public,anon;grant execute on function public.register_license_evidence(uuid,text,text,text,text,text,integer,integer,text)to authenticated;
comment on table public.license_evidence_documents is'Immutable metadata for AES-256-GCM Form-2, DC letter, and current-license evidence.';
