-- Durable reconciliation queue for encrypted Drive uploads whose compensating deletion fails.
create table public.drive_cleanup_queue(
 id uuid primary key default gen_random_uuid(),center_id uuid not null references public.centers(id),drive_file_id text not null unique check(char_length(drive_file_id)between 10 and 255),drive_path_key text not null check(char_length(drive_path_key)between 5 and 500),source_type text not null check(source_type in('application_document','staff_document','center_logo','license_evidence')),reason text not null check(char_length(reason)between 5 and 500),status text not null default'pending'check(status in('pending','resolved','failed')),attempt_count integer not null default 0 check(attempt_count between 0 and 100),last_error text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),resolved_by uuid references public.profiles(id),resolved_at timestamptz,updated_at timestamptz not null default now(),check((status='resolved'and resolved_by is not null and resolved_at is not null)or status<>'resolved')
);
create index drive_cleanup_pending_idx on public.drive_cleanup_queue(status,created_at)where status<>'resolved';
create trigger drive_cleanup_set_updated_at before update on public.drive_cleanup_queue for each row execute function private.set_updated_at();
create trigger drive_cleanup_prevent_delete before delete on public.drive_cleanup_queue for each row execute function private.prevent_receipt_mutation();
alter table public.drive_cleanup_queue enable row level security;alter table public.drive_cleanup_queue force row level security;
create policy drive_cleanup_review_read on public.drive_cleanup_queue for select to authenticated using(private.is_super_admin()or private.is_center_manager(center_id));
revoke all on public.drive_cleanup_queue from anon,authenticated;grant select on public.drive_cleanup_queue to authenticated;
create or replace function public.queue_drive_cleanup(p_center_id uuid,p_drive_file_id text,p_drive_path_key text,p_source_type text,p_reason text)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare rid uuid;actor_role public.user_role;begin
 actor_role:=private.current_role();if actor_role not in('owner','operator')or not private.mfa_satisfied()then raise exception'Operational MFA required';end if;if p_center_id<>private.current_center_id()then raise exception'Center mismatch';end if;if char_length(p_drive_file_id)not between 10 and 255 or char_length(p_drive_path_key)not between 5 and 500 or p_source_type not in('application_document','staff_document','center_logo','license_evidence')or char_length(trim(p_reason))not between 5 and 500 then raise exception'Invalid cleanup record';end if;
 insert into public.drive_cleanup_queue(center_id,drive_file_id,drive_path_key,source_type,reason,created_by)values(p_center_id,p_drive_file_id,p_drive_path_key,p_source_type,trim(p_reason),auth.uid())on conflict(drive_file_id)do update set reason=excluded.reason,status=case when drive_cleanup_queue.status='resolved'then drive_cleanup_queue.status else'pending'end returning id into rid;
 perform private.write_audit_log(p_center_id,'drive.cleanup_queued','drive_cleanup',rid,jsonb_build_object('source_type',p_source_type,'drive_path_key',p_drive_path_key));return rid;
end;$$;
create or replace function public.resolve_drive_cleanup(p_cleanup_id uuid,p_success boolean,p_error text default null)returns void language plpgsql security definer set search_path=pg_catalog,public,private as $$declare item public.drive_cleanup_queue%rowtype;begin
 if not private.is_super_admin()or not private.mfa_satisfied()then raise exception'Super Admin AAL2 required';end if;select*into item from public.drive_cleanup_queue where id=p_cleanup_id for update;if not found or item.status='resolved'then raise exception'Pending cleanup not found';end if;if not p_success and char_length(trim(coalesce(p_error,'')))not between 5 and 500 then raise exception'Failure detail required';end if;
 update public.drive_cleanup_queue set status=case when p_success then'resolved'else'failed'end,attempt_count=attempt_count+1,last_error=case when p_success then null else trim(p_error)end,resolved_by=case when p_success then auth.uid()else null end,resolved_at=case when p_success then now()else null end where id=item.id;
 perform private.write_audit_log(item.center_id,case when p_success then'drive.cleanup_resolved'else'drive.cleanup_failed'end,'drive_cleanup',item.id,jsonb_build_object('attempt',item.attempt_count+1,'error',case when p_success then null else trim(p_error)end));
end;$$;
revoke execute on function public.queue_drive_cleanup(uuid,text,text,text,text),public.resolve_drive_cleanup(uuid,boolean,text)from public,anon;grant execute on function public.queue_drive_cleanup(uuid,text,text,text,text),public.resolve_drive_cleanup(uuid,boolean,text)to authenticated;
comment on table public.drive_cleanup_queue is'Audited reconciliation queue for encrypted uploads left behind only when metadata registration and compensating Drive deletion both fail.';
