-- Audited invitation acceptance and revocation lifecycle for Owner and Operator accounts.
create table public.account_invitations(
 id uuid primary key default gen_random_uuid(),center_id uuid not null references public.centers(id),invitee_profile_id uuid not null references public.profiles(id),invitee_email text not null check(invitee_email=lower(invitee_email)and char_length(invitee_email)between 5 and 320),invitation_role public.user_role not null check(invitation_role in('owner','operator')),status text not null default'pending'check(status in('pending','accepted','revoked','expired')),invited_by uuid not null references public.profiles(id),invited_at timestamptz not null default now(),expires_at timestamptz not null,accepted_at timestamptz,revoked_at timestamptz,revoked_by uuid references public.profiles(id),revocation_reason text,check(expires_at>invited_at),check((status='accepted'and accepted_at is not null)or status<>'accepted'),check((status='revoked'and revoked_at is not null and revoked_by is not null and char_length(revocation_reason)between 5 and 500)or status<>'revoked')
);
create unique index account_invitations_pending_profile_idx on public.account_invitations(invitee_profile_id)where status='pending';create index account_invitations_center_idx on public.account_invitations(center_id,status,invited_at desc);
alter table public.account_invitations enable row level security;alter table public.account_invitations force row level security;
create policy account_invitations_read on public.account_invitations for select to authenticated using(private.is_super_admin()or(private.current_role()='owner'and center_id=private.current_center_id()and private.mfa_satisfied())or invitee_profile_id=auth.uid());
revoke all on public.account_invitations from anon,authenticated;grant select on public.account_invitations to authenticated;
create trigger account_invitations_prevent_delete before delete on public.account_invitations for each row execute function private.prevent_receipt_mutation();
create or replace function public.register_account_invitation(p_profile_id uuid,p_center_id uuid,p_role public.user_role,p_email text)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare rid uuid;actor_role public.user_role;begin
 actor_role:=private.current_role();if not private.mfa_satisfied()or not((actor_role='super_admin'and p_role='owner')or(actor_role='owner'and p_role='operator'and p_center_id=private.current_center_id()))then raise exception'Invitation authority required';end if;
 if p_role not in('owner','operator')or lower(trim(p_email))!~'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'or not exists(select 1 from public.profiles p where p.id=p_profile_id and p.center_id=p_center_id and p.role=p_role and lower(p.email)=lower(trim(p_email)))then raise exception'Assigned invitation profile mismatch';end if;
 update public.account_invitations set status='expired'where invitee_profile_id=p_profile_id and status='pending'and expires_at<=now();
 insert into public.account_invitations(center_id,invitee_profile_id,invitee_email,invitation_role,invited_by,expires_at)values(p_center_id,p_profile_id,lower(trim(p_email)),p_role,auth.uid(),now()+interval'7 days')returning id into rid;
 perform private.write_audit_log(p_center_id,'account.invitation_registered','account_invitation',rid,jsonb_build_object('profile_id',p_profile_id,'role',p_role,'expires_at',now()+interval'7 days'));return rid;
end;$$;
create or replace function public.accept_my_account_invitation()returns void language plpgsql security definer set search_path=pg_catalog,public,private as $$declare item public.account_invitations%rowtype;begin
 select*into item from public.account_invitations where invitee_profile_id=auth.uid()and status='pending'order by invited_at desc limit 1 for update;if not found then return;end if;if item.expires_at<=now()then update public.account_invitations set status='expired'where id=item.id;update public.profiles set is_active=false where id=auth.uid();return;end if;
 update public.account_invitations set status='accepted',accepted_at=now()where id=item.id;perform private.write_audit_log(item.center_id,'account.invitation_accepted','account_invitation',item.id,jsonb_build_object('profile_id',auth.uid()));
end;$$;
create or replace function public.revoke_account_invitation(p_invitation_id uuid,p_reason text)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare item public.account_invitations%rowtype;actor_role public.user_role;begin
 actor_role:=private.current_role();if not private.mfa_satisfied()or char_length(trim(p_reason))not between 5 and 500 then raise exception'Valid revocation authority and reason required';end if;select*into item from public.account_invitations where id=p_invitation_id for update;if not found or item.status<>'pending'or item.expires_at<=now()then raise exception'Pending invitation not found';end if;if not(actor_role='super_admin'or(actor_role='owner'and item.center_id=private.current_center_id()and item.invitation_role='operator'))then raise exception'Invitation revocation forbidden';end if;
 update public.account_invitations set status='revoked',revoked_at=now(),revoked_by=auth.uid(),revocation_reason=trim(p_reason)where id=item.id;update public.profiles set is_active=false where id=item.invitee_profile_id;
 if item.invitation_role='owner'then update public.center_owner_assignments set ended_at=now(),end_reason='Invitation revoked: '||trim(p_reason)where owner_profile_id=item.invitee_profile_id and center_id=item.center_id and ended_at is null;end if;
 perform private.write_audit_log(item.center_id,'account.invitation_revoked','account_invitation',item.id,jsonb_build_object('profile_id',item.invitee_profile_id,'role',item.invitation_role,'reason',trim(p_reason)));return item.invitee_profile_id;
end;$$;
revoke execute on function public.register_account_invitation(uuid,uuid,public.user_role,text),public.accept_my_account_invitation(),public.revoke_account_invitation(uuid,text)from public,anon;grant execute on function public.register_account_invitation(uuid,uuid,public.user_role,text),public.accept_my_account_invitation(),public.revoke_account_invitation(uuid,text)to authenticated;
comment on table public.account_invitations is'Seven-day invitation lifecycle with immutable history, explicit acceptance, and pre-acceptance revocation.';
