-- Public Center registration requests with explicit Super Admin review; requests never create active tenants directly.
create table public.center_registration_requests(id uuid primary key default gen_random_uuid(),name text not null check(char_length(name)between 3 and 160),location_type public.location_type not null,division text not null,district text not null,upazila text not null,union_or_ward text,address text not null,phone text not null,email text not null,license_number text,license_expires_at date,applicant_name text not null,applicant_declaration boolean not null check(applicant_declaration),status text not null default'pending'check(status in('pending','approved','rejected')),reviewed_by uuid references public.profiles(id),review_note text,created_center_id uuid references public.centers(id),submitted_at timestamptz not null default now(),reviewed_at timestamptz,check(phone~'^01[3-9][0-9]{8}$'),check(email=lower(email)),check((status='pending'and reviewed_at is null)or(status<>'pending'and reviewed_at is not null and reviewed_by is not null and char_length(review_note)between 10 and 1000)));
create unique index center_registration_pending_email on public.center_registration_requests(email)where status='pending';create unique index center_registration_pending_phone on public.center_registration_requests(phone)where status='pending';create index center_registration_status_idx on public.center_registration_requests(status,submitted_at);
alter table public.center_registration_requests enable row level security;alter table public.center_registration_requests force row level security;create policy center_registration_super_read on public.center_registration_requests for select to authenticated using(private.is_super_admin()and private.mfa_satisfied());revoke all on public.center_registration_requests from anon,authenticated;grant select on public.center_registration_requests to authenticated;
create trigger center_registration_prevent_delete before delete on public.center_registration_requests for each row execute function private.prevent_receipt_mutation();
create or replace function public.submit_center_registration(p_name text,p_location_type public.location_type,p_division text,p_district text,p_upazila text,p_union_or_ward text,p_address text,p_phone text,p_email text,p_license_number text,p_license_expires_at date,p_applicant_name text,p_declaration boolean,p_website text default null)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare rid uuid;begin
 if coalesce(trim(p_website),'')<>''or not coalesce(p_declaration,false)then raise exception'Invalid submission';end if;if char_length(trim(p_name))not between 3 and 160 or char_length(trim(p_division))not between 2 and 80 or char_length(trim(p_district))not between 2 and 80 or char_length(trim(p_upazila))not between 2 and 80 or char_length(trim(p_address))not between 5 and 500 or char_length(trim(p_applicant_name))not between 2 and 120 or p_phone!~'^01[3-9][0-9]{8}$'or lower(trim(p_email))!~'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'or char_length(coalesce(p_license_number,''))>120 then raise exception'Invalid registration information';end if;
 insert into public.center_registration_requests(name,location_type,division,district,upazila,union_or_ward,address,phone,email,license_number,license_expires_at,applicant_name,applicant_declaration)values(trim(p_name),p_location_type,trim(p_division),trim(p_district),trim(p_upazila),nullif(trim(p_union_or_ward),''),trim(p_address),p_phone,lower(trim(p_email)),nullif(trim(p_license_number),''),p_license_expires_at,trim(p_applicant_name),true)returning id into rid;return rid;exception when unique_violation then raise exception'A pending request already exists';end;$$;
create or replace function public.review_center_registration(p_request_id uuid,p_approve boolean,p_center_code text,p_note text)returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$declare r public.center_registration_requests%rowtype;cid uuid;begin
 if not private.is_super_admin()or not private.mfa_satisfied()then raise exception'Super Admin AAL2 required';end if;if char_length(trim(p_note))not between 10 and 1000 then raise exception'Review note required';end if;select*into r from public.center_registration_requests where id=p_request_id for update;if not found or r.status<>'pending'then raise exception'Pending registration not found';end if;
 if p_approve then if upper(trim(p_center_code))!~'^LSFC-[A-Z0-9-]{3,24}$'then raise exception'Valid Center code required';end if;insert into public.centers(code,name,location_type,division,district,upazila,union_or_ward,address,phone,email,license_number,license_expires_at,status)values(upper(trim(p_center_code)),r.name,r.location_type,r.division,r.district,r.upazila,r.union_or_ward,r.address,r.phone,r.email,r.license_number,r.license_expires_at,'pending')returning id into cid;insert into public.center_status_history(center_id,previous_status,new_status,reason,changed_by)values(cid,null,'pending','Approved public registration request: '||trim(p_note),auth.uid());end if;
 update public.center_registration_requests set status=case when p_approve then'approved'else'rejected'end,reviewed_by=auth.uid(),review_note=trim(p_note),created_center_id=cid,reviewed_at=now()where id=r.id;perform private.write_audit_log(cid,case when p_approve then'center.registration_approved'else'center.registration_rejected'end,'center_registration',r.id,jsonb_build_object('request_id',r.id,'center_code',p_center_code));return cid;
end;$$;
revoke execute on function public.submit_center_registration(text,public.location_type,text,text,text,text,text,text,text,text,date,text,boolean,text),public.review_center_registration(uuid,boolean,text,text)from public;grant execute on function public.submit_center_registration(text,public.location_type,text,text,text,text,text,text,text,text,date,text,boolean,text)to anon,authenticated;grant execute on function public.review_center_registration(uuid,boolean,text,text)to authenticated;
comment on table public.center_registration_requests is'Public registration intake requiring explicit AAL2 Super Admin approval before a pending Center is created.';
