import type { Metadata } from "next";
import { History, Power, ShieldCheck, ToggleLeft } from "lucide-react";
import { ServiceToggleForm } from "@/components/services/ServiceToggleForm";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
export const metadata:Metadata={title:"Service feature controls"};
type Service={code:string;name_bn:string;description_bn:string|null;sort_order:number;is_active:boolean};
type Change={id:string;service_code:string;previous_state:boolean;new_state:boolean;reason:string;changed_at:string};
export default async function ServicesPage(){await requireRole(["super_admin"]);const sb=await createClient();const[{data:serviceData},{data:historyData}]=await Promise.all([sb.from("services").select("code,name_bn,description_bn,sort_order,is_active").order("sort_order"),sb.from("service_availability_history").select("id,service_code,previous_state,new_state,reason,changed_at").order("changed_at",{ascending:false}).limit(10)]);const services=(serviceData??[]) as Service[];const history=(historyData??[]) as Change[];const active=services.filter(s=>s.is_active).length;
return <div><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-xs font-bold text-brand"><ToggleLeft className="size-4"/> Global rollout</div><h1 className="mt-2 text-2xl font-extrabold sm:text-3xl">Government-service controls</h1><p className="mt-2 text-sm text-muted">১৪টি সেবা nationwide ON/OFF করুন।</p></div><div className="flex w-fit items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-xs font-bold text-emerald-800"><ShieldCheck className="size-4"/> {active}/{services.length} service active</div></div>
<div className="mb-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-[11px] leading-6 text-amber-900"><strong>নিরাপদ rollout:</strong> কোনো service OFF করলে নতুন application intake থেকে তা সঙ্গে সঙ্গে অদৃশ্য হবে। আগে তৈরি হওয়া application বাতিল বা পরিবর্তিত হবে না।</div>
<section className="grid gap-4 lg:grid-cols-2">{services.map(service=><article key={service.code} className={`rounded-2xl border bg-white p-5 shadow-sm ${service.is_active?"border-border":"border-red-200"}`}><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className={`grid size-10 shrink-0 place-items-center rounded-xl text-xs font-extrabold ${service.is_active?"bg-brand-soft text-brand":"bg-red-50 text-red-700"}`}>{String(service.sort_order).padStart(2,"0")}</div><div><h2 className="text-sm font-extrabold">{service.name_bn}</h2><p className="mt-1 font-mono text-[9px] text-muted">{service.code}</p></div></div><span className={`flex shrink-0 items-center gap-1.5 rounded-full px-2.5 py-1 text-[9px] font-extrabold ${service.is_active?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}><Power className="size-3"/>{service.is_active?"ON":"OFF"}</span></div>{service.description_bn&&<p className="mt-3 text-[10px] leading-5 text-muted">{service.description_bn}</p>}<ServiceToggleForm serviceCode={service.code} active={service.is_active}/></article>)}</section>
<section className="mt-6 rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-2"><History className="size-5 text-brand"/><h2 className="text-base font-extrabold">সাম্প্রতিক rollout history</h2></div>{history.length===0?<p className="py-10 text-center text-xs text-muted">এখনো কোনো service অবস্থা পরিবর্তন হয়নি</p>:<div className="mt-5 grid gap-3 lg:grid-cols-2">{history.map(change=><div key={change.id} className="rounded-xl border border-border p-4"><div className="flex items-start justify-between gap-3"><p className="font-mono text-[10px] font-bold text-brand">{change.service_code}</p><span className={`rounded-full px-2 py-1 text-[8px] font-extrabold ${change.new_state?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{change.new_state?"ENABLED":"DISABLED"}</span></div><p className="mt-2 text-[10px] text-muted">{change.reason}</p><time className="mt-2 block text-[9px] text-muted">{new Intl.DateTimeFormat("bn-BD",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Dhaka"}).format(new Date(change.changed_at))}</time></div>)}</div>}</section></div>}
